aleph-im/aleph-vm

- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
- vm_supervisor/vm/firecracker_microvm.py
Both from resolv.conf (Debian) and from systemd-resolved (Ubuntu).
This requires setting the configuration `VM_DNS_RESOLUTION=resolvectl` on systems using `systemd-resolved` and rebuilding the runtime image.
> Enhancement: Add support to extract DNS servers from host

- firecracker/__init__.py
- firecracker/config.py
- firecracker/microvm.py
- vm_supervisor/vm/firecracker_microvm.py
> WIP: Refactor: Configure Firecracker using JSON file

- .github/workflows/test-integration-fakedata.yml
- docker/run_vm_supervisor.sh
- docker/vm_supervisor.dockerfile
- runtimes/aleph-debian-11-python/create_disk_image.sh
- runtimes/aleph-debian-11-python/init0.sh
- runtimes/aleph-debian-11-python/init1.py
- runtimes/aleph-debian-11-python/update_inits.sh
- vm_supervisor/README.md
- vm_supervisor/storage.py
Fixes #38
Some stats:
- Alpine runtime weights 329M (ext4)
- Debian runtime weights 438M (ext4)
- Debian Squashfs weights 186M
> Switch to a Debian based runtime, using SquashFS instead of ext4

- vm_supervisor/pool.py
- vm_supervisor/run.py
The first request was returning an error message to clients, but subsequent requests were keeping the connection open with no response.
> Fix: Pool stored VM with failed setup

- runtimes/aleph-debian-11-python/create_disk_image.sh
> Fix: Ethereum tools require eth_account, absent from runtime

- guest_api/__main__.py
- packaging/aleph-vm/DEBIAN/control
This adds the use of `setproctitle` to change the title of the process for easier diagnostic.
> Feature: Admin could not distinguish guest_api among running processes

- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/conf.py
- vm_supervisor/vm/firecracker_microvm.py
This sets the default level to INFO and a setting to configure the level wanted.
Warning: This breaks the ConfigurationPayload schema, VMs will need to update their runtime/init first.
> WIP: Log level inside VMs was always DEBUG

- vm_supervisor/messages.py
The supervisor was returning 404 Hash not found when any dependency of the program was missing with no further detail.
This helps the user debugging by returning the missing hash.
> Fix: Users could now identify missing hash

- README.md
- doc/INSTALL-Debian-11.md
- doc/INSTALL-Ubuntu-20.04.md
- doc/INSTALL.md
The documentation about the installation procedure in the main README.md was mixed with other topics and contained if-else for Debian/Ubuntu.
This splits the doc in different files for each supported host operating system.
> Doc: Package installation was difficult to follow

- vm_supervisor/pool.py
Solution: Allow execution to be already missing.
See Sentry error https://sentry.io/organizations/alephim/issues/3001246903/?project=6193637&query=is%3Aunresolved
> Fix: forget_vm called twice when VM init times out

- vm_supervisor/__main__.py
Solution: Initiate the database in the benchmark procedure.
An alternative would be to make the database optional and ignore it in benchmarks.
> Fix: Database access during benchmarks errored

- vm_supervisor/templates/index.html
- vm_supervisor/views.py
The information is already in the HTTP headers, but those are not trivial to access.
Solution: Display the version info on the index page, and whether it is up-to-date.
Fetch information about the latest version from the browser, and only on demand, so no request to GitHub is done by the server.
Fixes #164
> Feature: User could not easily access the current version of the software

- vm_supervisor/vm/firecracker_microvm.py
During VM teardown, the field AlephFirecrackerVM().guest_api_process._popen
could be None, and the following traceback be raised:
```python
File "/root/aleph-vm/vm_supervisor/models.py", line 116, in create
await vm.teardown()
File "/root/aleph-vm/vm_supervisor/vm/firecracker_microvm.py", line 429, in teardown
await self.stop_guest_api()
File "/root/aleph-vm/vm_supervisor/vm/firecracker_microvm.py", line 424, in stop_guest_api
self.guest_api_process.terminate()
File "/usr/lib/python3.8/multiprocessing/process.py", line 133, in terminate
self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```
> Fix: AttributeError crashed VM teardown

- vm_supervisor/conf.py
`self.__annotations__` did not include attributes with implicit type annotation (the type of the default value), and those were therefore not displayed when using `--print-settings`
> Fix: Settings with implicit annotations were not displayed

- vm_supervisor/metrics.py
- vm_supervisor/models.py
- vm_supervisor/vm/firecracker_microvm.py
Not the cleanest code due to duplication, but the most simple I could think of.
> Fix: Recording VM usage crashed if process had stopped beforehand

- vm_supervisor/views.py
The endpoint '/status/check/fastapi' is monitored by multiple operators
and therefore called very frequently. The crash handling check results
in a new virtual machine being started at every call, and memory leaks
(likely pipes accumulating) can cause the supervisor to crash after
some time with 'Too many open files'.
In the short term, avoid calling the crash check in the monitored endpoint.
In the longer term, investigate and fix the accumulating file descriptors.
> Fix: Stability issues when checking crash handling in monitored endpoint

- .github/workflows/build-deb-package.yml
- examples/volumes/Dockerfile
Due to an internal change in GitHub Actions, this started to fail.
This pull request fixes the issue and isolates the build of the runtime and the build of the example virtualenv volume.
> CI: Building example volume using Docker failed

- vm_supervisor/models.py
This would have been the source of many duplicate asyncio tasks.
> Fix: Watching for updates could be started multiple times

- vm_supervisor/pubsub.py
Mutating the object being iterated caused inconsistency when iterating over subscribers.
> Fix: Internal PubSub `msubscribe` failed

- .github/workflows/test-on-droplet.yml
- docker/vm_supervisor-dev.dockerfile
- packaging/aleph-vm/DEBIAN/control
- vm_supervisor/resources.py
- vm_supervisor/supervisor.py
The scheduling of persistent VMs requires external services to fetch the available system resources of the host.
Solution: Add a new HTTP endpoint on `/about/usage/system` that exposes system resources and system properties of the host machine.
> Feature: System resources were not exposed

- docker/vm_supervisor-dev.dockerfile
- examples/volumes/Dockerfile
- guest_api/__main__.py
- packaging/Makefile
- vm_supervisor/README.md
- vm_supervisor/conf.py
- vm_supervisor/models.py
- vm_supervisor/pool.py
- vm_supervisor/resources.py
- vm_supervisor/run.py
- vm_supervisor/supervisor.py
- vm_supervisor/utils.py
- vm_supervisor/views.py
The supervisor only supported on request execution of virtual machines.
This add support for an external scheduler to send a list of VMs that should be started and persisted.
A temporary simple HTTP authentication method is used to authenticate the scheduler, this is planned to move to P2P messages from Core Channel Nodes.
> Feature: VMs could not be persisted

- vm_supervisor/pubsub.py
We still support Ubuntu 20.04 that ships with Python 3.8.
Solution: Use a different typing annotation depending on the version of Python, making it easier to ditch the simpler annotation when Python 3.8 goes out of support.
Fixes #243
> Fix: Annotation was not supported by Python 3.8

- firecracker/microvm.py
- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/conf.py
- vm_supervisor/pool.py
- vm_supervisor/utils.py
- vm_supervisor/vm/firecracker_microvm.py
Previously, 172.0.0.0/8 range was hardcoded to be used as the pool for which to assign IP addresses out of. As this was in violation of RFC1918, this needed to change. As this meant reworking the code anyway, it was changed so the range is configurable. The code to determine the IPs was also moved up to the supervisor level instead of the vm level, as that is more appropriate place for the code to be. Fixes the first point of Issue #237
> Fix: Remove hardcoded 172.0.0.0/8 range from use to comply with RFC1918 

- .github/workflows/test-on-droplet.yml
Curl requires the `--fail` argument in order to return a code different than zero and raise and issue in the action.
> Fix: Curl did not error when test failed.

- vm_supervisor/conf.py
Problem: The supervisor could start while the virtualization device /dev/kvm was absent from the system.
Solution: Add a check in the initialization of the configuration for /dev/kvm to be present.
Fixes #269
> Fix: Supervisor started without /dev/kvm

- .github/workflows/build-deb-package.yml
- .github/workflows/test-build-examples.yml
Errors were encountered while processing:
grub-efi-amd64-signed
needrestart is being skipped since dpkg has failed
> Fix: GitHub actions failed on Ubuntu due to Grub

- vm_connector/main.py
Problem: launching the VM connector with `run_vm_connector.sh` yields
an exception because of issues with the return types of the API
endpoints.
Solution: remove `Response` and `StreamingResponse` type hints from
return values as they are not Pydantic models.
> Fix: VM connector does not start when run locally

- docker/vm_supervisor-dev.dockerfile
Problem: the VM supervisor Docker image does not work because of a missing dependency.
Solution: add `python3-nftables` to the Dockerfile.
> Fix: add nftables package to VM supervisor Dockerfile

- tests/supervisor/test_resolvectl_dns_servers.py
- vm_supervisor/conf.py
Problem: VMs do not support IPv6 networking, and therefore cannot make use of IPv6 DNS servers. Specifying one in resolv.conf blocks network access from inside the VM.
Solution: Filter out IPv6 DNS servers from the output of resolvectl
Additional fixes:
* Support parsing IPv6 addresses from resolvectl output
* Support newlines in resolvectl output
* Doc and type hints.
Added unit tests.
> Exclude IPv6 DNS servers when configuring VMs

- .github/workflows/code-quality.yml
- .github/workflows/codeql-analysis.yml
Problem 1: mypy check fails because it cannot import `Self` from typing_extensions. The solution is to upgrade typing-extensions in the CI workflow.
Problem 2: CodeQL action v1 is deprecated since Jan 18. The solution is to upgrade to v2.
> CI: use CodeQL action v2

- examples/instance_message_from_aleph.json
- kernels/microvm-kernel-x86_64-5.10.config
- vm_supervisor/vm/firecracker/executable.py
- vm_supervisor/vm/firecracker/instance.py
- vm_supervisor/vm/firecracker/program.py
Problem: Setup an instance using a cloud OS image file was impossible without a custom init file
Solution: Use the cloud-init tool already integrated in some cloud distributions to setup the network and system configuration.
> Use cloud-init tool to setup an Instance

- vm_supervisor/conf.py
- vm_supervisor/storage.py
- Fix: When the users runs a test instance, it cannot use fake runtime Solution: Update general settings adding FAKE_DATA_INSTANCE variable to use the fake rootfs or the real one.
- Fix: Conditions differ for fake path to runtime or rootfs
> Fork `get_runtime_path`

- vm_supervisor/network/firewall.py
The error message Debian 11:
```
python3[1910876]:     if not check_if_table_exists("ip", table):
python3[1910876]:   File "/opt/aleph-vm/vm_supervisor/network/firewall.py", line 91, in check_if_table_exists
python3[1910876]:     and entry["family"] == family
python3[1910876]: KeyError: 'family'
```
Solution: Use `.get()` instead of `__getitem__`
> Fix: Users reported errors with key `family` absent from entry

- firecracker/microvm.py
- runtimes/aleph-debian-11-python/init1.py
- vm_supervisor/utils.py
- vm_supervisor/vm/firecracker/program.py
Problem: the supervisor cannot deduce the version of the init process of the microVM runtime. This leads to compatibility issues when adding new features (like IPv6 support in this case).
Solution: define a version for the init process and send this value to the supervisor when the VM boots. This version is then used to gatekeep features when configuring the VM.
> Feature: microVM runtime version

- runtimes/aleph-debian-11-python/create_disk_image.sh
- runtimes/instance-debian-rootfs/Dockerfile
Problem: With the incoming support of IPv6, allowing login into virtual machines using SSH with a password becomes unacceptable.
Solution: Remove SSH password login from runtimes, as well as the root default password.
> Fix: Root login with shared password is insecure

- runtimes/instance-debian-rootfs/init1.py
- vm_supervisor/README.md
Include `/opt/node_modules` in the module resolution for node.js in order to allow the [Dependency Volume Builder](https://github.com/aleph-im/aleph-cloud-tools/tree/main/dependency_builder) to target this directory when building a dependency volume.
> Add default NODE_PATH env

- docker/vm_supervisor-dev.dockerfile
- firecracker/microvm.py
- packaging/aleph-vm/DEBIAN/control
- runtimes/aleph-debian-11-python/init1.py
- tests/supervisor/test_ipv6_allocator.py
- vm_supervisor/README.md
- vm_supervisor/conf.py
- vm_supervisor/network/hostnetwork.py
- vm_supervisor/network/interfaces.py
- vm_supervisor/network/ndp_proxy.py
- vm_supervisor/pool.py
- vm_supervisor/utils.py
- vm_supervisor/views.py
- vm_supervisor/vm/firecracker/executable.py
- vm_supervisor/vm/firecracker/instance.py
- vm_supervisor/vm/firecracker/program.py
- vm_supervisor/vm/vm_type.py
Problem: we want each VM to be reachable on the internet, with no restriction in terms of ports, protocols, etc.
Solution: slice up the IPv6 range attributed to each CRN and allocate a subnet to each VM.
By default, a /124 IPv6 range is assigned to each VM. The IPv6 range is based on the item hash of the VM. For a VM with item hash `cafecafecafecafe...` on a CRN with 1111:2222:3333:4444::/64, the VM will be reachable at 1111:2222:3333:4444:1:cafe:cafe:caf1.
We use NDP proxying by default, as some cloud operators do not route the full IPv6 range to the server.
This PR does not manage the problem of isolating the IPv6 address of the host. It is advised to isolate the host range in its own /80 (ex: `1111:2222:3333:4444:0::/80`). This can be achieved by either running the following script in …
> Feature: assign public IPv6 ranges to VMs

- firecracker/__init__.py
- firecracker/microvm.py
- vm_supervisor/conf.py
- vm_supervisor/network/hostnetwork.py
- vm_supervisor/network/interfaces.py
- vm_supervisor/network/ndp_proxy.py
Problems:
1. Operations on the NDP Proxy were synchronous.
2. Developing on the supervisor required the installation of the NDP Proxy.
Solutions:
1. Make operations on the NDP Proxy asynchronous.
2. Add setting `USE_NDP_PROXY` that permits users to disable the NDP Proxy.
> Fix: NDP Proxy was sync and mandatory

- vm_supervisor/vm/firecracker/executable.py
A property of a class was not used.
> Fix: Unused variable could be removed

- firecracker/__init__.py
- firecracker/microvm.py
- runtimes/aleph-debian-11-python/init1.py
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
- vm_supervisor/vm/firecracker/program.py
Problem: Users and developers could not specify SSH keys to connect inside the VM.
Solution: Add a configuration to VMs that forwards SSH public keys.
Allow developers to specify public keys in the configuration and enable these via a CLI argument.
When developer keys are used, keys from the message are ignored.
> Fix: Could not SSH into a program VM

- vm_supervisor/version.py
The supervisor would not start if the `apt` library is found but the `aleph-vm` package is not installed.
Solution: Handle cases when the package is not found and the apt cache returns None.
> Fix: Crash when getting version from apt

- runtimes/aleph-debian-11-python/init1.py
Problem: The version of init1.py defines some of the capabilities of the platform. This was not exposed to programs running inside virtual machines.
Solution: Expose the version as an environment variable.
> Feature: Init version was hard to fetch from programs

- packaging/aleph-vm/DEBIAN/control
Package python3-yaml is required to generate the cloud-init configuration.
Package python3-dotenv is required by Pydantic to load settings from a .env file during development.
> Fix: Missing dependencies in Debian package

- vm_supervisor/conf.py
- vm_supervisor/network/hostnetwork.py
- vm_supervisor/pool.py
Solution: Add a setting to disable IPv6 forwarding. Forwarding is enabled by default.
> Fix: IPv6 forwarding caused issue on some development servers.

- runtimes/aleph-debian-11-python/init1.py
Problem: The authorized_keys file could not be generated if the `config.authorized_keys` settings was None because it was used in a list comprehension.
Solution: check for None early.
> Fix: VM does not boot if no SSH key is specified

- tests/supervisor/test_ipv6_allocator.py
- vm_supervisor/views/__init__.py
The method `allocator.allocate_vm_ipv6_subnet` now requires the argument `vm_type`, which was not provided in the tests.
> Fix: Pytest failed due to missing argument

- .github/workflows/test-on-droplet-ubuntu-22.04.yml
Problem: the CI is looking for only one lock file, but apt/dpkg use several. Furthermore, `lslocks --json` seems to cut its output to a specific width, and configuration options (`--notruncate`) do not appear to have an impact.
Solution: repeat calls to apt-get update until we get the lock.
> Fix: CI for Ubuntu was failing too often because of apt/dpkg locks

- vm_supervisor/models.py
- vm_supervisor/pool.py
- vm_supervisor/snapshot_manager.py
Problems:
* the supervisor attempts to start snapshot jobs for programs, which we do not want to support.
* the supervisor does not stop the snapshot job for an instance when the instance is stopped.
Solutions:
* add a check to avoid the issue.
* pass the snapshot manager object to each VM execution to stop the snapshot task when the execution is stopped.
> Fix: only start snapshots for instances

- vm_supervisor/resources.py
Problem: the Allocation model requires a value to be specified for the `persistent_vms` field.
Solution: default to an empty set.
> Fix: allow allocations without persistent VMs

- vm_supervisor/vm/firecracker/instance.py
Problem: the current network config file is incompatible with Debian 11. This appears to be because the `network` key is not required.
Solution: remove the `network` key and put its content directly in the dictionary.
> Fix: remove the `network` key from the cloud-init network file

- vm_supervisor/storage.py
This fix solves the problem that we found when you add a block device with higher size that are snapshots from another devices with less size.
We created a linear block device that uses the image one but with the correct final size, and we create the snapshot using this new base device as base.
> Fixed multiple block device size issues

- packaging/Makefile
- packaging/debian-12.dockerfile
- vm_supervisor/messages.py
- vm_supervisor/snapshot_manager.py
- vm_supervisor/snapshots.py
- vm_supervisor/storage.py
- vm_supervisor/vm/firecracker/instance.py
Feature: Restore existing VM snapshots if exists on Aleph.
> Restore existing snapshots

- packaging/aleph-vm/etc/systemd/system/ipfs.service
Problem: in normal mode, the IPFS daemon advertises itself with private addresses. Some cloud providers do not like this at all and will send abuse notices related to port scanning.
Solution: start the daemon with the server profile, which only advertises the node with public addresses and avoids port scanning.
> Fix: start IPFS daemon with the server profile

- examples/example_fastapi/main.py
- vm_supervisor/status.py
Problem: a node operator reports a timeout when attempting to connect to `https://9.9.9.9`. However, he can ping `9.9.9.9` just fine.
Solution: as the diagnostic check is targeted at IPv4 connectivity only, use a socket to attempt to connect to 9.9.9.9:53 directly.
> Fix: no HTTPs in IPv4 diagnostic check

- doc/INSTALL-Debian-11.md
- doc/INSTALL-Debian-12.md
- doc/INSTALL-Ubuntu-22.04.md
The syntax of the Caddyfile documented in the quick install guides is broken in Caddy 2.7.4.
This removes the unused `on_demand` section from the configuration, restoring compatibility with newer versions of Caddy.
We maintain the `on_demand_tls` section in case we may re-enable wildcard domains on the default config.
```diff
{
on_demand_tls {
interval 60s
burst 5
}
}
brain01.crn.alephians.com:443 {
-        tls {
-              on_demand
-        }
reverse_proxy http://127.0.0.1:4020 {
header_up Host {host}
}
}
```
> Fix: Caddyfile syntax broken in 2.7.4

- .github/workflows/test-on-droplet-ubuntu-22.04.yml
- doc/INSTALL-Debian-12.md
- doc/INSTALL-Ubuntu-22.04.md
- vm_supervisor/conf.py
Operators had to specify network interface and DNS resolver while can be done automatically.
The network interfaces defaulted to `eth0`, which not the default on all supported systems.
This uses the default network interface instead, and should require less configuration from node operators and developers.
The DNS resolver defaulted to `resolv.conf`, which is not the default on all supported systems.
This adds an option to detect if systemd-resolved is available, and else defaults to `/etc/resolv.conf`.
> Automate network and DNS settings

- runtimes/aleph-debian-11-python/init1.py
The only Mypy error left is related to the use of the type `ASGIApplication`, defined as:
```python
ASGIApplication = NewType("ASGIApplication", Any)
```
```
init1.py:46: error: Argument 2 to NewType(...) must be subclassable (got "Any")  [valid-newtype]
```
I did not find any easy solution for that. It does not seem blocking.
> Cleanup: Fix Mypy errors in init1.py

- vm_supervisor/conf.py
- vm_supervisor/run.py
The Diagnostics VM checks for the proper handling of exceptions.
This fills the logs with noisy stack traces.
Solution: Add a setting that defaults to ignoring that specific error and stacktrace.
> Fix: Noisy tracebacks filled logs

- .github/workflows/code-quality.yml
- docker/run_vm_supervisor.sh
- examples/example_http_js/src/run.sh
- packaging/extract_requirements.sh
- runtimes/aleph-debian-11-python/init0.sh
- runtimes/aleph-debian-11-python/init1.py
- runtimes/instance-rootfs/create-debian-11-disk.sh
- runtimes/instance-rootfs/create-debian-12-disk.sh
- vm_supervisor/conf.py
- vm_supervisor/metrics.py
- vm_supervisor/storage.py
- vm_supervisor/views/__init__.py
- vm_supervisor/views/operator.py
- vm_supervisor/vm/firecracker/executable.py
- vm_supervisor/vm/firecracker/program.py
- Cleanup: Fix Mypy errors in init1.py
- Fix: Code quality was not enforced
- Cleanup: Code quality issues reported by tooling.
> Enhance code quality checks

- firecracker/microvm.py
- vm_supervisor/run.py
- vm_supervisor/storage.py
- vm_supervisor/views/__init__.py
- vm_supervisor/vm/firecracker/instance.py
- vm_supervisor/vm/firecracker/program.py
Solved shutdown errors that prevent the VM to try again to be scheduled on the CRN.
Errors:
- Property `_unix_socket` is not used on instances yet, so initialize to `None` by default.
- If the VM don't respond to a ping, should forget the VM to be able to try to power up later.
- Improvement: Use `fallocate` instead `dd` command to create empty files.
- Fixed cloud-init issue that only executes the configuration on the first boot. Now, if the VM ID has changed, the cloud-init configuration re-runs again.
- Ensure that the allocation process don't stop, either, on a VM failure.
> Solved some VM errors

- .github/workflows/build-deb-package.yml
- .github/workflows/test-build-examples.yml
- .github/workflows/test-new-runtime-examples.yml
- runtimes/aleph-debian-12-python/create_disk_image.sh
- runtimes/aleph-debian-12-python/init0.sh
- runtimes/aleph-debian-12-python/init1.py
- runtimes/aleph-debian-12-python/loading.html
- runtimes/aleph-debian-12-python/update_inits.sh
This adds a new runtime based on Debian 12.
Use `diff` to compare the two versions since some files are copied.
```diff
sepal@basecamp ~/R/a/a/runtimes (hoh-runtime-debian-12)> diff aleph-debian-1*
diff '--color=auto' aleph-debian-11-python/create_disk_image.sh aleph-debian-12-python/create_disk_image.sh
10c10
< debootstrap --variant=minbase bullseye ./rootfs http://deb.debian.org/debian/
---
> debootstrap --variant=minbase bookworm ./rootfs http://deb.debian.org/debian/
19c19
<   socat libsecp256k1-0 \
---
>   socat libsecp256k1-1 \
22c22
<   python3-setuptools \
---
>   python3-setuptools python3-venv \
26a27
>   python3-fastapi \
34,40c35,41
< pip3 install 'fastapi~=0.95.1'
< 
< echo "Pip installing aleph-client"
< pip3 install 'aleph-sdk-python==0.7.0'
< 
< # Compile all Python …
```
> Fix: Program runtime could use newer Debian 12

- packaging/Makefile
Problem: Setting a value for `SENTRY_DNS` often did not work because the Sentry SDK was not installed.
The Sentry SDK has a very limited number of dependencies.
Solution: Install the Sentry SDK by default from the Debian packages.
> Fix: Sentry SDK was absent from most installs

- packaging/aleph-vm/DEBIAN/postinst
- packaging/aleph-vm/DEBIAN/postrm
- packaging/aleph-vm/DEBIAN/preinst
- packaging/aleph-vm/etc/systemd/system/ipfs.service
Systemd provides hardening tools to improve the security of the host.
This uses the hardened service file from the Kubo repository.
> Fix: The Kubo IPFS service was not hardened

- vm_supervisor/supervisor.py
Solution: Display a clear error message when the port is already in use.
> Fix: Unclear stacktrace when port in used already

- runtimes/aleph-debian-11-python/create_disk_image.sh
- runtimes/aleph-debian-12-python/create_disk_image.sh
Problem: Debian 12 runtime has FastAPI 0.92.0 (installed from apt) while Debian 11 runtime has FastAPI 0.95.1. Some VMs previously running on the Debian 11 runtime do not run on the Debian 12 runtime because of this issue.
Solution: install the latest version of FastAPI from PyPI.
> Fix: install FastAPI from PyPI in Debian 12 runtime

- .github/workflows/code-quality.yml
- examples/example_fastapi/main.py
Solution: Expose os-release, Python version and installed Python packages via the example_fastapi diagnostic VM.
> Fix: Diagnostic did not expose platform information

- runtimes/aleph-debian-11-python/init1.py
By appending the path `/opt/packages` to the Python Path, system packages were loaded in priority. This prevented users from shipping their own versions of packages also present on the OS.
> Fix: System packages had priority over user installed

- vm_supervisor/conf.py
- vm_supervisor/status.py
- vm_supervisor/views/__init__.py
This upgrades it to use the newer Debian 12 runtime.
The new diagnosis VM adds extra enpoints, and supports the newer "Lifespan" ASGI API.
> Fix: Diagnosis VM used the old runtime.

- packaging/Makefile
See changelogs on https://github.com/firecracker-microvm/firecracker/releases
> Update: Firecracker 1.3.3 -> 1.5.0

- src/aleph/vm/controllers/firecracker/snapshot_manager.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/__init__.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/pool.py
Problem: VMPool and SnapshotManager class are coupled to orchestrator path.
Solution: Refactor VMPool and SnapshotManager classes to decouple it.
> Refactor VMPool class

- src/aleph/vm/network/hostnetwork.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/pool.py
Problem: Initializing the VM Pool had the side effect of setting up the network interfaces.
Solution: Move the setup of the networking in a separate method of the Network class, that has to be called explicitly.
> Fix: Initializing VM Pool had side effects

- src/aleph/vm/conf.py
The value set by the user for CACHE_ROOT and EXECUTION_ROOT were not respected when calculating the default value of MESSAGE_CACHE, CODE_CACHE, EXECUTION_DATABASE, etc...
Solution:
This was caused by the default value being defined at class definition, this patch move the defaults computation into Settings.check() so we have the user passed settings.
Reproduce the problem:
1. Without setting MESSAGE_CACHE
2. set CACHE_ROOT (via environment variable ALEPH_VM_CACHE_ROOT)
3. Print the settings  e.g ALEPH_VM_CACHE_ROOT=/tmp/ aleph-vm --do-not-run --print-settings
What was happening:
MESSAGE_CACHE = /var/cache/aleph/vm/message
What is expected and is happening now:
MESSAGE_CACHE = /tmp/message
> Problem: CACHE_ROOT & EXECUTION_ROOT not respected

- src/aleph/vm/conf.py
- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/network/firewall.py
- src/aleph/vm/orchestrator/run.py
This PR fix various crash and wrong warnings that were caused by a combination of configurations which  occurred when setting up my development environments.
These were mainly caused by:
- not having the jailman user (and USE_JAILER=0)
- not having the ndppd command (and USE_NDP=0)
- not running as root
-  disabling the network options via `--no-network`
The main solutions for theses were being more strict in respecting the user settings, better error handling and displaying better errors messages. 
Since it a lot of small fixes I estimated it was better to make them all in one PR
> Fix configuration edge cases

- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
Problem: In order to help troubleshooting a node, access to the logs or configuration files were required.
This proposal exposes fields that should not cause any issue being made public, as well as the value of some settings that should not be changed in production and could worry users.
> Fix: Public configuration fields were not exposed

- .github/workflows/test-on-droplets-matrix.yml
Solution: Add an option to `apt` commands to wait for the lock with a timeout.
> Fix: CI could not get lock on Ubuntu

- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/storage.py
- Fix: Integrity of runtime filesystems was not checked
- Fix: Prevent concurrent downloads and failed attempts
This branch improves the integrity of files downloaded using the following two methods:
1. Check the squashfs integrity of program runtimes
2. Prevent parallel downloads of files that could cause issues in file integrity
> Improve download integrity

- src/aleph/vm/hypervisors/firecracker/microvm.py
After the vm proc and the related stdout and stderr were closed the task keep trying to read them, creating a busy loop which wasted cpu.
Solution: end the task when the file descriptor is closed
> Problem: print_log tasks keep reading after vm end

- src/aleph/vm/orchestrator/views/operator.py
This fix the error cascade that happened when opening the logs endpoint not as websocket. This was problematic because it returned to the http client a 500 error instead of the actual error code and message
To reproduce
* start aleph supervisor
* open in Firefox: http://localhost:4020/vm/3fc0aa9569da840c43e7bd2033c3c580abb46b007527d6d20f2d4e98e867f7af
* then in another tab http://localhost:4020/control/machine/3fc0aa9569da840c43e7bd2033c3c580abb46b007527d6d20f2d4e98e867f7af/logs
```
Error that happened before
2023-11-16 16:16:58,089 | ERROR | Error handling request Traceback (most recent call last):
File "/home/ubuntu/remote-aleph/src/aleph/vm/orchestrator/views/operator.py", line 147, in stream_logs
await ws.prepare(request)
File …
```
> Fix errors cascade on Websocket.prepare() error

- .github/workflows/pr-rating.yml
Add PR Difficulty Rating workflow, see: https://github.com/aleph-im/aleph-sdk-python/pull/76
> PR Difficulty Rating Workflow

- src/aleph/vm/hypervisors/firecracker/microvm.py
This made representation in the log like this
`<aleph.vm.hypervisors.firecracker.microvm.MicroVM object at 0x7fa7f4f1ca90> 2092.023134 |V DEBUG | Init received msg`
Solution : Add a `__str__` method on MicroVM
> Problem: MicroVM had no str which made log ugly

- .github/workflows/test-on-droplets-matrix.yml
Solution: Start the same diagnostic VM as instance, instead to use the old one, use the matrix value.
> Fix issue scheduling instance on CI

- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/pool.py
This branch adds 3 fixes regarding the concurrency of launching the same VM multiple times
in a short period of time, before the setup of the other instances has finished.
- Fix: Ordering issue in starting persistent VM
- Fix: Two executions for the same VM could be prepared in parallel
- Fix: A VM could be prepared in parallel
> Fixes regarding concurrency

- src/aleph/vm/conf.py
- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
it was hardcoded before on /var/lib/aleph so it wasn't respecting the proper user settings and was failling if the user didn't have the correct permission for this folder and was producing warning
> Make JAILER_BASE_DIR dependend on execution root

- src/aleph/vm/orchestrator/views/__init__.py
RuntimeError: dictionary changed size during iteration
Solution:
make a copy of the executions list before altering it
To reproduce.
----
You will need to set ALEPH_VM_ALLOCATION_TOKEN_HASH= and pass the corresponding signatures:
Launch both debian VMs
```http
POST http://localhost:4020/control/allocations
Content-Type: application/json
X-Auth-Signature: test
Accept: application/json
{"persistent_vms": [], "instances": ["67705389842a0a1b95eaa408b009741027964edc805997475e95c505d642edd8", "3fc0aa9569da840c43e7bd2033c3c580abb46b007527d6d20f2d4e98e867f7af"]}
```
Stop all instances
```http
POST http://localhost:4020/control/allocations
Content-Type: application/json
X-Auth-Signature: test
Accept: application/json
{"persistent_vms": [], "instances": []}
```
```pyhon3-traceback
Traceback (most …
```
> Problem: Exception when stopping multiple VM via allocation endpoint

- src/aleph/vm/orchestrator/run.py
This caused an error while the processes calling this do check for the execution to become ready.
> Fix: Concurrent creation resulted in no `execution.vm`

- packaging/aleph-vm/DEBIAN/control
- pyproject.toml
- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/orchestrator/views/operator.py
Solution : Log the VM logs in journald and query journald when we need to retrieve the logs.
For this I create two log streams per VM, one for stdout and one for stderr, using the ability from the journald api to just directly retrieve a file descriptor that we can pass to subprocess_exec.
This way should allow for maximum performance since we don't need to handle the insertion in the log system in python but we let journald directly manage it.
I only did the Qemu controller as a demonstration I will do the other part and the systemd integration if the teams validate this approach.
Note that this is using the official systemd python binding (the one that is packaged in debian, as python3-systemd) and not the `systemd` package in Pypi which is another project completly (and it is very …
> Problem: Log system won't work when we switch to systemd

- doc/INSTALL-Debian-11.md
- doc/INSTALL-Debian-12.md
- doc/INSTALL-Ubuntu-22.04.md
Hey :wave: 
Fixed a link to the documentation to configure Caddy and bumped version to install to `0.3.1` :smile:
> fix(docs): Broken link to Caddy documentation and version bump

- src/aleph/vm/orchestrator/views/static/helpers.js
Fixes an error when loading the metrics graph due to missing metrics message. 
This fix, however may add incomplete data sets to the metrics graph (see below)
> Fix: Metrics graph not loading due to a "TypeError"

- packaging/aleph-vm/DEBIAN/control
Fix targetting the systemd branch.
> Fix: Library `dbus` was missing on Debian 12 hosts.

- src/aleph/vm/conf.py
- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/controllers/firecracker/instance.py
- src/aleph/vm/controllers/firecracker/program.py
- src/aleph/vm/models.py
- src/aleph/vm/network/hostnetwork.py
- src/aleph/vm/orchestrator/metrics.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/pool.py
- src/aleph/vm/systemd.py
- src/aleph/vm/utils.py
Problem: When the node operator restarts the orchestrator with already running persistent VMs, at the start, it doesn't get already running persistent VMs.
Solution: Use the SQLite database to save all the executions and re-create it from the start.
> Load already running persistent VMs

- README.md
The link to Debian 12 install instructions was missing
> added missing Debian 12 install doc link

- src/aleph/vm/orchestrator/tasks.py
Fix: We are not managing well the holding tier on instances, so will be better to disable that control.
> Solve holding tier issue for instances

- src/aleph/vm/orchestrator/views/host_status.py
Problem:
The endpoint `/status/check/host` should return a data structure with details about the networking that works or does not.
When IPv6 connectivity failed due to a connection error, the endpoint crashed with an error 500 instead of returning the expected value `false` for that type of connectivity.
Solution: Wrap connectivity errors with a try-catch.
> Fix: Connectivity errors crashed the endpoint

- src/aleph/vm/models.py
Fixes the following error, reported by node operators.
```
task: <Task finished name='Task-1' coro=<_run_app() done, defined at /usr/lib/python3/dist-packages/aiohttp/web.py:287> exception=AttributeError("'NoneType' object has no attribute 'to_dict'")>
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/aiohttp/web.py", line 431, in _run_app
await asyncio.sleep(delay)
File "/usr/lib/python3.10/asyncio/tasks.py", line 605, in sleep
return await future
asyncio.exceptions.CancelledError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/aiohttp/web.py", line 433, in _run_app
await runner.cleanup()
File "/opt/aleph-vm/aleph/vm/models.py", line 234, in stop
await self.record_usage() …
```
> Fix: AttributeError when `self.vm` == None

- src/aleph/vm/orchestrator/tasks.py
This reduces the log level to warning and does not print the stacktrace.
We also add the `item_hash` in the logs for diagnostic as it was missing.
Previously, logs looked like:
```
2024-02-02 10:16:59,290 | ERROR | Invalid Aleph message:
[
{
"loc": [
"content",
"payment"
],
"msg": "extra fields not permitted",
"type": "value_error.extra"
}
]
[ErrorWrapper(exc=ValidationError(model='InstanceContent', errors=[{'loc': ('payment',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}]), loc=('content',))]
Traceback (most recent call last):
File "/opt/aleph-vm/aleph/vm/orchestrator/tasks.py", line 63, in subscribe_via_ws
yield parse_message(data)
File "/opt/aleph-vm/aleph_message/models/__init__.py", line 366, in parse_message
return message_class.parse_obj(message_dict)
File …
```
> Fix: Logs of invalid messages were too verbose

- src/aleph/vm/orchestrator/tasks.py
Solution: Catch and handle the IndexError.
> Fix: An IndexError was raised if no execution was left for this sender.

- src/aleph/vm/orchestrator/views/__init__.py
This code used the wrong class for the timeout exception.
> Fix: TypeError: catching classes that do not inherit from BaseException is not allowed

- examples/example_fastapi/main.py
- src/aleph/vm/orchestrator/views/host_status.py
A user reported that this function crashed on his host due to `ValueError: too many values to unpack (expected 2)`.
Solution: Process each returned tuple instead of assuming that two of them are always returned.
This fixes the issue both in the orchestrator and in the diagnostic VM.
> Fix: `socket.getaddrinfo` does not always return 2 values

- packaging/Makefile
- pyproject.toml
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/utils.py
Fix: Implemented CORS support on supervisor endpoints.
> Added CORS support on supervisor endpoints

- src/aleph/vm/conf.py
- src/aleph/vm/utils.py
If the Linux kernel provided is was another device than the execution root, creating a hardlink within the jailer directory would fail.
Solution: Copy the kernel to the execution root during setup.
> Fix: Linux kernel from package could not be on a different device

- examples/example_fastapi/main.py
Problem: Diagnostic VM API isn't accessible through frontend.
Solution: Implement CORS policy headers on diagnostic VM endpoints.
> Implement CORS on diagnostic VM endpoints

- src/aleph/vm/orchestrator/views/__init__.py
Fix: Check request token exists before compare it to secret token of app.
Solves issue on Sentry `onsupported operand types or combination of types: 'NoneType' and 'str'`
> Check request token exists

- src/aleph/vm/pool.py
When attempting to stop the pool, the `stop()` method expected a tuple `vm_hash, execution` while the function called to provide thos only returned an iterable of executions.
Solution: Discard the `vm_hash`.
> Fix: Caller expected tuple but got a single value

- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/run.py
Problem: Sometimes, when a VM expires, the execution is not removed.
Solution: Check if the namespace stills there and if not just remove the execution.
> Solve random 500 errors on ephemeral VMs

- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/pool.py
- Fix: A VM was only marked as stopping after all runs completed
- Fix: Stopping executions could be returned
> Fix issues with stopping VMs

- pyproject.toml
- src/aleph/vm/conf.py
- src/aleph/vm/controllers/firecracker/instance.py
- src/aleph/vm/controllers/firecracker/program.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/hypervisors/firecracker/config.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
- src/aleph/vm/models.py
- src/aleph/vm/network/interfaces.py
- src/aleph/vm/orchestrator/pubsub.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/pool.py
- src/aleph/vm/systemd.py
Depends on https://github.com/aleph-im/aleph-vm/pull/555 - Fix: Caller expected tuple but got a single value
Changes:
- Fix: Type checks were not enforced
- Fix: Mypy configuration was inline
> Use stronger typing with Mypy

- runtimes/aleph-debian-11-python/create_disk_image.sh
- runtimes/aleph-debian-12-python/create_disk_image.sh
Some packages cannot run using the current runtime with its default locale settings:
```shell
C
C.UTF-8
POSIX
```
This pull request enhances package stability by adding support for the en_US.UTF-8 locale.
> Runtimes: Update locale settings to en_US UTF-8

- src/aleph/vm/orchestrator/cli.py
This could result in invalid settings being used by the software.
> Fix: Benchmark command did not initialize or check settings

- src/aleph/vm/network/interfaces.py
Solution: Always use `check=True` to force errors in `subprocess.run` to raise an error.
> Fix: Errors in network interface manipulation were invisible

- src/aleph/vm/conf.py
- src/aleph/vm/controllers/firecracker/snapshot_manager.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/pool.py
`asyncio.run` was called when initializing a pool object using `VmPool.__init__(...)`.
This caused two issues:
1. The pool was sometimes created from within a coroutine in the context of tests, and this would raise an error.
2. Having side effects inside the `__init__` method makes objects more difficult to manipulate and test.
3. Tests should not load persistent executions automatically.
4. The network was configured after loading persistent executions, which could cause networking issues.
A related issue is the snapshot manager being started when initializing the `VmPool`, while this is not always desirable.
Solution proposed:
1. Explicitly load the persistent executions using `pool.load_persistent_executions()` from the `supervisor.run()` function. This is now called after …
> Fix: asyncio.run was sometimes used within a coroutine

- .github/workflows/test-on-droplets-matrix.yml
- packaging/Makefile
- pyproject.toml
- src/aleph/vm/network/interfaces.py
- tests/supervisor/test_interfaces.py
Context: We recently added the argument `check=True` to `subprocess.run(command)` to ensure we do not ignore errors in the setup or teardown of network interfaces.
Problem: Analyzing the errors that may happen during the setup or teardown of network interfaces is difficult due to the little amount of information provided by the `ip` command. It is therefore difficult to react accordingly.
Solution: Switch to use `pyroute2`, a pure Python netlink library that provides the required functions with more fined grained error reports.
The library `Pyroute2` is available in Debian 12 [1], however that version (0.7.2-2) is not documented anymore. It is absent from Debian 11. We therefore use the latest stable version from PyPI.
[1] https://packages.debian.org/bookworm/python3-pyroute2
> Fix: Network errors were hard to inspect

- src/aleph/vm/conf.py
Fix: If the `FAKE_DATA_PROGRAM` variable have a default value, when we start the controllers, it takes that default value instead to avoid it, and it fails on the checks.
Solution: Put `FAKE_DATA_PROGRAM` variable to None by default.
> Fix `FAKE_DATA_PROGRAM` issue on instances.

- src/aleph/vm/conf.py
- src/aleph/vm/models.py
Problem: The unique way to set the default hypervisor to use is hard-coded on the `models.py` class, so we can't select another one by default.
Solution: Implement `INSTANCE_DEFAULT_HYPERVISOR` field on the orchestrator configuration variables.
> Implement default hypervisor options on settings

- src/aleph/vm/network/interfaces.py
- tests/supervisor/test_interfaces.py
Calling `delete_tap_interface` on an interface that is not present raised an error. This logs a debug message instead.
When the interface is not found for adding an IP address or setting a link up, a more explicit error is raised.
> Fix: Deleting a missing interface crashed

- src/aleph/vm/network/interfaces.py
When attempting to schedule a Firecracker instance, the error below came in a loop.
Solution: Log a warning instead of raising an exception.
```
2024-03-19 15:45:49,346 | ERROR |   File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/opt/aleph-vm/aleph/vm/orchestrator/__main__.py", line 4, in <module>
main()
File "/opt/aleph-vm/aleph/vm/orchestrator/cli.py", line 371, in main
supervisor.run()
File "/opt/aleph-vm/aleph/vm/orchestrator/supervisor.py", line 163, in run
web.run_app(app, host=settings.SUPERVISOR_HOST, port=settings.SUPERVISOR_PORT)
File "/opt/aleph-vm/aiohttp/web.py", line 544, in run_app
loop.run_until_complete(main_task)
File "/usr/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
self.run_forever() …
```
> Fix: Interface being busy prevented instance creation

- src/aleph/vm/network/ndp_proxy.py
The `ndppd` service is not always required and restarting it can fail.
While waiting for a better fix that prevents restarting the service too quickly, this logs an error instead of raising an exception.
> Fix: Failing to restart `nddpd` caused the exception to escalate

- src/aleph/vm/controllers/firecracker/executable.py
The parent directory on which the Guest APi listens did not exist in some context (probably Firecracker based instances), which crashed the process.
This ensures that the directories exist and that the Unix socket can therefore be created.
> Fix: Guest API would crash due to FileNotFound

- src/aleph/vm/network/interfaces.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/pool.py
Problem: After the change of the new interface library to handle network interfaces, when you call 2 VMs at the same time, it assigns to you the same VM_ID and the network setup fails.
Solution: Implement semaphores on the execution creation to avoid creating VMs at the same time.
* Avoid raising exceptions on network issues and just log it as error.
* Added missing await async on VM request handling
> Solve network issues on Ubuntu hosts

- .github/workflows/test-on-droplets-matrix.yml
The command `hatch run testing:cov` includes running `hatch run testing:test-cov`.
This removes the duplication
> Fix: Tests were run twice

- examples/example_django/example_django/asgi.py
- examples/example_fastapi/main.py
- packaging/version_from_git.py
- runtimes/aleph-debian-11-python/init1.py
- src/aleph/vm/conf.py
- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/controllers/firecracker/program.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/guest_api/__main__.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/cli.py
- src/aleph/vm/orchestrator/metrics.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/authentication.py
- src/aleph/vm/pool.py
- src/aleph/vm/storage.py
- tests/supervisor/test_jwk.py
- vm_connector/main.py
This branch fixes a series of errors reported when using strict typing checks with the tool `mypyc`
I recommend reviewing these changes one commit at a time.
Not not squash.
- Fix typing: web.HTTPBadRequest may not be raised
- Fix typing: Wrong type in annotation
- Fix typing: FakeRequest class was not of type Request
- Fix typing: Invalid type annotations
- Fix typing: Replace Dict->dict, List->list
- Fix typing: SQLAlchemy annotations were incorrect
- Fix typing: Missing return types on methods
- Fix typing: Strict type checks raised issues
- Fix: Properties were initialized with a global object
- fixup! Fix typing: Replace Dict->dict, List->list
- Fix typing: `...` in class is not allowed
- Fix typing: `continue` inside try/finally block is unimplemented in `mypyc`
- Fix typing: Use of …
> Fix strict typing errors

- pyproject.toml
- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/orchestrator/views/__init__.py
- tests/supervisor/test_views.py
- Fix: Error data was JSON encoded twice
- Fix: Invalid ItemHash did not raise a ValidationError
Do not squash.
See the details of each commit for more information.
In particular:
Fix: Invalid ItemHash did not raise a ValidationError
Problem: Posting invalid item hashes to the `update_allocations` API failed far after the initial validation, with:
```   File "/opt/aleph-vm/aleph_message/models/item_hash.py", line 25, in from_hash
raise UnknownHashError(f"Could not determine hash type: '{item_hash}'")
aleph_message.exceptions.UnknownHashError: Could not determine hash type: '${{ matrix.check_vm.item_hash }}'
```
Solution: Require ItemHash as part of the `Allocation` schema, in order to fail validation earlier, in the section dedicated to the validation of the uploaded data.
> Validation of ItemHash on allocations raised wrong error

- src/aleph/vm/orchestrator/cli.py
Problem  happened when launching with --run-fake-instance
Solution: Adapt to new VMPool API that take a loop Also fix benchmarks function
> Problem: could not start Instances from command line

- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/authentication.py
Fix: Solve last CORS errors raised cause by duplication of headers returned.
> Solve last CORS issues about duplicated headers

- .github/workflows/test-on-droplets-matrix.yml
- examples/example_fastapi/README.md
- examples/example_fastapi/main.py
- runtimes/aleph-debian-12-python/create_disk_image.sh
- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/orchestrator/status.py
- src/aleph/vm/orchestrator/views/__init__.py
We published multiple changes to the diagnostic VM recently but none of these was released.
This provides a new diagnostic VM, based on a new runtime [1], with fixes:
- Reading messages with the newer SDK
- Better handling of IPv6 detection errors
- Two different tests for signing messages (local and remote)
- aleph-message version was not specified
- fetching a single message was not tested
> Update the diagnostic VM

- .github/workflows/test-on-droplets-matrix.yml
- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/orchestrator/supervisor.py
- tests/supervisor/test_views.py
Solution: Add a test in pytest and a  test in droplet
I had to refactor the setup of the web.app test since pytest-aiohttp use a new async loop between each tests.
Also fixed an issue in `get_machine_properties` where the returned format is not the same between all the machines. note that this code/dep  is going to be dropped in #544 so that's not a blocking issue
> Problem /about/usage/system was not tested

- runtimes/aleph-debian-11-python/create_disk_image.sh
- runtimes/aleph-debian-12-python/create_disk_image.sh
When executed using `bash`, the `create_disk_image` was interrupted by a Python REPL due to the `python -OO` command being surrounded by backquotes.
> Fix: Backquote in shell script executed command

- .github/workflows/test-on-droplets-matrix.yml
- .github/workflows/test-using-pytest.yml
Problem: Running system testing on DigitalOcean for every push consumed a lot of resources and failed frequently.
We now start to have integration testing using `pytest`, which provides a better confidence that things actually work.
Solution: Only test on DO open Pull Requests and not every push. In the future, consider only running when merged on `main`.
> Fix: System testing on DO took too many resources

- .github/workflows/test-on-droplets-matrix.yml
- .github/workflows/test-using-pytest.yml
- pyproject.toml
- runtimes/instance-rootfs/create-ubuntu-22-04-qemu-disk.sh
- src/aleph/vm/conf.py
- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/controllers/qemu/__init__.py
- src/aleph/vm/models.py
- tests/supervisor/test_qemu_instance.py
Feature: Added automatic tests to check if Qemu runs, also with network interface.
The tests bypass systemd manager to reduce complexity.
In later tests we will test the entire flow also using systemd.
> Added Qemu automatic tests

- .github/workflows/deploy-main-on-staging.yml
This deploys the main branch automatically on the staging servers for system testing.
> Fix: Branch `main` could not be tested easily

- .github/workflows/deploy-main-on-staging.yml
- .github/workflows/test-on-droplets-matrix.yml
- .github/workflows/test-using-pytest.yml
- examples/instance_message_from_aleph.json
- pyproject.toml
- runtimes/instance-rootfs/create-ubuntu-22-04-qemu-disk.sh
- src/aleph/vm/conf.py
- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/controllers/qemu/__init__.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/views/__init__.py
- tests/supervisor/test_instance.py
- tests/supervisor/test_instances.py
- tests/supervisor/test_qemu_instance.py
- tests/supervisor/views/test_run_code.py
Feature: Added tests to check if Firecracker instance runs with network interface.
The tests bypass systemd manager
> 601 creating instance tests

- src/aleph/vm/utils.py
Problem: Reading a file using `f.open().read()` keeps the file open until the garbage collector deletes the variable.
Since this uses Pathlib already, using `Path(...).read_text()` is cleaner and does not depend on the opening mode being `r`.
A file with no content could not be distinguished from a missing file. Instead, this changes the behaviour to return None when the file is missing instead of an empty string.
> Minor code cleanup in check_system_module

- .github/workflows/build-deb-package.yml
- packaging/Makefile
- packaging/ubuntu-24.04.dockerfile
This adds support in the packaging/Makefile and in the CI to build packages for Ubuntu 24.04
> Fix: No .deb was built for Ubuntu 24.04

- src/aleph/vm/conf.py
Problem: The server doesn't have a directory to save the platform certificates generated by `sevctl`.
Solution: Set that directory field on settings class and ensure to create the folder on initialization step.
> Add platform confidential directory on Settings

- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/sevclient.py
- tests/supervisor/test_views.py
Problem: There isn't an endpoint to be able to get the confidential platform certificates to start the VM key exchange.
Solution: Create that endpoint and return the platform certificates generated by the `sevctl` command.
> Implement get platform certificates endpoint

- src/aleph/vm/orchestrator/status.py
- tests/supervisor/test_status.py
Problem:
The diagnostic VM returned HTTP 200 with {"result": False} when it could not connect to the internet.
Since this is an OK return code, `raise_for_status` did not raise an error and an assertion error was raised.
Solution:
Test that the returned status code also corresponds to HTTP OK.
Stacktrace:
```
Jun 05 10:39:20 testing-hetzner python3[1400146]: vm-5 1851967.687130 |V DEBUG | <<<
Jun 05 10:39:20 testing-hetzner python3[1400146]: vm-5
Jun 05 10:39:25 testing-hetzner python3[1400146]: vm-5 2024-06-05 10:39:25,688 | ERROR | Error handling request
Jun 05 10:39:25 testing-hetzner python3[1400146]: Traceback (most recent call last):
Jun 05 10:39:25 testing-hetzner python3[1400146]:   File "/opt/aleph-vm/aiohttp/web_protocol.py", line 452, in _handle_request
Jun 05 10:39:25 …
```
> Fix: Orchestrator failed with `assert result["result"] == HTTPOk.status_code`

- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/operator.py
The auth function in websocket was crashing when the header  "X-Auth-Signature" wasn't passed, even  that authentification method wasn't used.
Make it an option in the method so we can still have error raised in normal header auth
> Problem: Crash when trying to auth via websocket

- examples/confidential_instance_message_from_aleph.json
- pyproject.toml
- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/controllers/configuration.py
- src/aleph/vm/controllers/qemu/client.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/controllers/qemu_confidential/instance.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
- src/aleph/vm/hypervisors/qemu_confidential/qemuvm.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/authentication.py
- src/aleph/vm/orchestrator/views/operator.py
- tests/supervisor/test_views.py
Add the Qemu confidential controler, and endpoints to retrieve the measurements.
> Ol qemu confidential controller

- .dockerignore
- .github/workflows/build-deb-package.yml
- .github/workflows/test-on-droplets-matrix.yml
- .gitignore
- packaging/Makefile
- packaging/debian-11.dockerfile
- packaging/debian-12.dockerfile
- packaging/ubuntu-22.04.dockerfile
- packaging/ubuntu-24.04.dockerfile
- src/aleph/vm/conf.py
Solution: Build `sevctl` using an upstream version of Rust (the version in Debian is not supported), and bundle it in the Debian packages.
Add a setting in aleph-vm with the path of the bundled binary.
> Fix: Binary `sevctl` was absent from debian packages

- docker/vm_supervisor-dev.dockerfile
- examples/volumes/Dockerfile
- packaging/Makefile
- pyproject.toml
- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/README.md
- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/utils/__init__.py
- tests/supervisor/test_utils.py
Trusted computing requires CPU features such as `sev`, `sev_es` and `sev_snp`.
This adds the field `properties.cpu.features` `/about/usage/system` as a list of CPU features.
Currently, only SEV related features are present, but more can be added, for example `avx2`, `fma` and `f16c`. Adding them will require ensuring that they are actually active and not just present on the CPU via `/proc/cpuinfo`.
This work is based on a proposal to add the relevant field on aleph-message: https://github.com/aleph-im/aleph-message/pull/100
Example JSON output:
```json
{
"cpu": {
"count": 12,
"load_average": {
"load1": 0.31494140625,
"load5": 0.1806640625,
"load15": 0.17138671875
},
"core_frequencies": {
"min": 2200,
"max": 3600
}
},
"mem": {
"total_kB": 16663798,
"available_kB": 13188161
},
"disk": { …
```
> Fix: CRN API did not expose CPU features for trusted computing

- src/aleph/vm/orchestrator/views/authentication.py
- tests/supervisor/test_authentication.py
Problem: If a user wants to manage different operations for a different CRNs, they have to sign a new pubkey token for every CRN, and this is so bad for the user experience.
Solution: Move the `domain` field to the operation token payload instead the pubkey one, just to improve the user experience and maintain the security integrity.
> Move `domain` payload field to Operation token instead PubKey one

- src/aleph/vm/controllers/interface.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/utils/logs.py
- src/aleph/vm/utils/test_helpers.py
- tests/supervisor/test_authentication.py
- tests/supervisor/views/test_operator.py
Solution: Provide a view that works in get
not sure about the endpoint name.
It's just a proposal to see if it is interesting to have it Still have to fix  the style and doc but want to gather your feed back first
> Problem: Websocket were required to fetch logs

- runtimes/instance-rootfs/create-debian-11-qemu-disk.sh
- runtimes/instance-rootfs/create-debian-12-qemu-disk.sh
- src/aleph/vm/hypervisors/firecracker/microvm.py
Problem: If an instance is created and removed, one of the base mounted devices remains on the system. Also, a user cannot create a `Qemu` disk from Debian image.
Solution: Remove the useless device from the system and create the two needed script to create `Qemu` Debian runtimes.
> Improve instances code

- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
Error reported on https://github.com/aleph-im/aleph-vm/issues/652
> Fix: AttributeError: 'MicroVM' object has no attribute 'send_shutdown_message'

- packaging/Makefile
Problem: The supervisor cannot start a new instance because there is a missing `cpuid` dependency.
Solution: Add missing `cpuid` dependency to `Makefile` to add it on the Debian and Ubuntu packages.
> Add missing `cpuid` dependency

- src/aleph/vm/orchestrator/views/operator.py
- tests/supervisor/views/test_operator.py
Problem: If the frontend or a user send and incorrect auth payload, the endpoint just stop sharing data without return anything or close the connection.
Solution: Handle error issues on the endpoint to always return status field and the reason why it's failing, and closing the connection.
> Solve Websocket error handling

- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/orchestrator/status.py
Problem: If the server doesn't have access to Internet, it just crashes. Also, if an instance is removed, it fails removing the base block device.
Solution: Handle the crash and log as an error about the Internet connection. Check if the mounted block devices exist before removing it.
> Small fixes noticed on new installations.

- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
Problem: If the frontend or a user send the request to reboot a Firecracker instance, it stops but doesn't start again.
Solution: Change method to restart it just stopping the process, cleaning the firecracker run files and starting it again.
> Solve Firecracker reboot issues

- src/aleph/vm/conf.py
Problem: If a user wants to launch a Qemu instance inside a CRN, by default the support is disabled.
Solution: Enable the support by default and disable snapshots because aren't used.
> Enable Qemu support by default

- .github/workflows/test-using-pytest.yml
- pyproject.toml
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/models.py
- src/aleph/vm/pool.py
This branch mitigate some of the concurrency issue found during the confidential beta test that prevented some instances from being run or getting in  weird state.
> Mitigate concurrency issues

- src/aleph/vm/network/hostnetwork.py
- src/aleph/vm/pool.py
occasionaly vm creation vm because the assigned tap network inteface was already existing. Probably not properly teared down from a previous execution or from a concurrency issue
Displayed Error was :
OSError: [Errno 16] Device or resource busy
it was then looped as a retry and blocked the whole thing
Solution:
When assigning a vm_id, check that the network interface for that vm doesn't already exists This act as a double check for a variety of issues
> Problem: Vm execution failed due to network interface

- src/aleph/vm/orchestrator/supervisor.py
Solution: Display logging token at info logging level
> Problem: Login token was not display with default conf

- src/aleph/vm/orchestrator/status.py
Endpoint `/status/check/fastapi` was raising error when there was no internet inside vm
This was caused by `check_internet` raising an error instead of just returning False
Note: Contrarely to what was previously understood the diagnostic vm don't return a headers when the result is False.
Previous stacktrace
```
ValueError: The server cannot connect to Internet
File "aiohttp/web_app.py", line 537, in _handle
resp = await handler(request)
File "aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
File "aleph/vm/orchestrator/supervisor.py", line 70, in server_version_middleware
resp: web.StreamResponse = await handler(request)
File "aleph/vm/orchestrator/views/__init__.py", line 215, in status_check_fastapi
"internet": await status.check_internet(session, …
```
> Problem: status_check_fastapi endpoint raising eror

- src/aleph/vm/models.py
This was causing an error in the monitor payment task
```
AttributeError: 'FunctionEnvironment' object has no attribute 'trusted_execution'
File "aleph/vm/utils/__init__.py", line 90, in run_and_log_exception
return await coro
File "aleph/vm/orchestrator/tasks.py", line 154, in monitor_payments
executions = [execution for execution in executions if execution.is_confidential]
File "aleph/vm/orchestrator/tasks.py", line 154, in <listcomp>
executions = [execution for execution in executions if execution.is_confidential]
File "aleph/vm/models.py", line 113, in is_confidential
return True if self.message.environment.trusted_execution else False
```
Run a program so it's in the execution lists for example a permanent one,
Then wait for the monitory_payments task to run
> Fix is_confidential property

- src/aleph/vm/orchestrator/messages.py
- src/aleph/vm/orchestrator/tasks.py
- tests/supervisor/test_status.py
Problem: If a user allocates a VM and later forgets the VM, the payment task fails because cannot get the price for that execution.
Solution: Check the message status before checking the price and remove the execution if it is forgotten or on a different status than `processed`.
> Check message status before checking the payment

- src/aleph/vm/network/interfaces.py
- src/aleph/vm/pool.py
- tests/supervisor/test_status.py
Problem: If the service restarts, the diagnostic VM fails for network issues.
Solution: Loading already loaded VMs filtering by only persistent ones. Also remove the network interface if exists and re-create it.
> Solve duplicated network issues for ephemeral VMs

- .github/PULL_REQUEST_TEMPLATE.md
As discussed, providing these informations on each PR should improve review and code quality
> Provide a template for new PRs

- .github/workflows/test-using-pytest.yml
- examples/example_fastapi/main.py
- runtimes/aleph-debian-11-python/init1.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/storage.py
- tests/supervisor/test_execution.py
This PR solve a few issue with the tests:
- test_create_execution Was VERY VERY slow, more than 10 minutes to run. -> Now it run in less than 1 minutes
- test_create_execution_online  and test_create_execution_legacy were actually running the same test as test_create_execution. (because of a settings contamination) Which compelled the problem and made the whole test suite take 3/4h to run
- Additionally the code path of running a real program wasn't tested
- The Workflow name was not correct
- Execution test  of a program were failing on python 3.12
see above
Everything is in CI
> Fix CI slowness and correct  execution tests

- src/aleph/vm/controllers/firecracker/instance.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/utils/__init__.py
Symptoms:
Could not allocate a VM on some ubuntu server because the wait_for_init/ping
was failing
```
2024-09-03 12:18:47,259 | DEBUG | command: ping -c 1 -W 2.0 172.16.4.2
2024-09-03 12:18:47,259 | ERROR | Command failed with error code 1:
stdin = None
command = ['ping', '-c', '1', '-W', '2.0', '172.16.4.2']
stdout = b"ping: invalid value (`2.0' near `.0')\n"
2024-09-03 12:18:47,260 | ERROR |
Traceback (most recent call last):
File "/home/olivier/pycharm/aleph-vm/src/aleph/vm/utils/__init__.py", line 186, in ping
await run_in_subprocess(["ping", "-c", str(packets), "-W", str(timeout), host], check=True)
File "/home/olivier/pycharm/aleph-vm/src/aleph/vm/utils/__init__.py", line 121, in run_in_subprocess
raise subprocess.CalledProcessError(process.returncode, str(command), …
```
> Problem: ping: invalid value (`2.0' near `.0')

- packaging/Makefile
- pyproject.toml
- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/chain.py
- src/aleph/vm/orchestrator/payment.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/views/__init__.py
Problem: 
Base chain isn't supported.
Solutions:
adding `src/aleph/vm/orchestrator/chain.py` to store Available Chains
Display available_payments in status_public_config
Adding checks that the chains sent is in the `STREAM_CHAINS`
> Feature: Allow PAYG on base

- .github/workflows/test-using-pytest.yml
Sometime in test-using-pytest CI workflow the previous job failed, for example
[here](https://github.com/aleph-im/aleph-vm/actions/runs/10687238972/job/29624379941?pr=689),
and this line with `if: always()` won't be able to run because hatch is
installed in the previous step but this step might get skipped.
Always install hatch in this `always` step of the job.
Make a PR that will fail this job, for example by not respecting black or use
[act](https://github.com/nektos/act) to test that locally.
> ci/fix(test-using-pytest): ensure hatch is always installed when needed

- src/aleph/vm/hypervisors/firecracker/microvm.py
There was a teardown() inside a __del__
which was triggered by the garbage collection
This resulted in an unclear lifecycle and strange log error since the teardown was already triggered before and made for strange error when running tests
Solution: remove it
> Problem: Non deterministic teardown

- tests/supervisor/test_execution.py
- tests/supervisor/test_instance.py
- tests/supervisor/test_qemu_instance.py
The execution and instances tests were failing if the runtime or dis image were not properly set up but it was not clear to the user why
Solution: 
Use xfail to display an user to the message on how to set up properly
> tests/supervisor/test_execution.py::test_create_execution XFAIL (Test
Runtime not setup. run `cd runtimes/aleph-debian-12-python && sudo ./create_disk_image.sh`)
> Problem: Test failing not clearly

- packaging/aleph-vm/etc/systemd/system/aleph-vm-controller@.service
- src/aleph/vm/controllers/__main__.py
When running the controller as a systemd service (the normal usecase in prod) and stopping the service
the QEMU process was always killed BEFORE the shutdown command could be sent
so the VM could not properly clean up
As an additional symptom this error appeared and confused dev and user
```
Sep 05 12:24:03 testing-hetzner python3[2468548]: 2024-09-05 12:24:03,187 | ERROR | Task exception was never retrieved
Sep 05 12:24:03 testing-hetzner python3[2468548]: future: <Task finished name='Task-3' coro=<QemuVM.stop() done, defined at /opt/aleph-vm/aleph/vm/hypervisors/qemu/qemuvm.py:149> exception=QMPCapabilitiesError()>
Sep 05 12:24:03 testing-hetzner python3[2468548]: Traceback (most recent call last):
Sep 05 12:24:03 testing-hetzner python3[2468548]:   File …
```
> Problem: QEMUVM killed before shutdown command

- src/aleph/vm/orchestrator/tasks.py
Iterating over the keys of a dictionary is a lazy operation that uses a generator under the hood.
An error was reported on Sentry due to "RuntimeError: dictionary changed size during iteration".
[Error on Sentry](https://alephim.sentry.io/share/issue/9327621b4aa44d7b80bb53ae7696590c/)
This error was introduced by @nesitor on PR https://github.com/aleph-im/aleph-vm/pull/679
This fixes the issue by transforming the generator into a list, which is the standard way to approach this issue in Python.
> Fix: dictionary changed size during iteration

- doc/operator_auth.md
- src/aleph/vm/orchestrator/views/authentication.py
- tests/supervisor/views/test_operator.py
All python version didn\'t return the same error
E         - {"status": "failed", "reason": "string indices must be integers"}
E         + {"status": "failed", "reason": "string indices must be integers, not \'str\'"}
Solution: Force a error message.
Should also make the message a bit clearer
> Problem: Test test_websocket_logs_invalid_auth fail on Python 3.12.3

- .github/workflows/test-on-droplets-matrix.yml
- Only calculate the IP once.
- Do not include the configuration inside the Debian package but modify it directly inside the droplet.
- [N/A] An LLM was used to review the new code and look for simplifications.
- [N/A] New classes and functions contain docstrings explaining what they provide.
- [of course] All new code is covered by relevant tests.
> Improve CI workflow for Droplet test

- src/aleph/vm/utils/__init__.py
Add missing return type type.
Just launch mypy (the CI should do it for you)
> feat: add return type to aleph.vm.utils.to_json

- pyproject.toml
Enable pyproject-fmt to uniformise pyproject.toml formatting accross all projects.
Related ClickUp, GitHub or Jira tickets : ALEPH-181
Just run:
```
hatch run lint:style
hatch run lint:fmt
```
> add pyproject-fmt

- .github/workflows/build-deb-package.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/deploy-main-on-staging.yml
- .github/workflows/pr-rating.yml
- .github/workflows/test-build-examples.yml
- .github/workflows/test-new-runtime-examples.yml
- .github/workflows/test-on-droplets-matrix.yml
- .github/workflows/test-using-pytest.yml
- pyproject.toml
Add yamlfix to uniformise yaml formatting everywhere.
Related ClickUp, GitHub or Jira tickets : ALEPH-180
Just run:
```
hatch run lint:style
hatch run lint:fmt
```
> feat: add yamlfix

- .github/workflows/test-using-pytest.yml
- pyproject.toml
This is to uniformise its name with other projects env names where "linting" is used everywhere.
> chore: rename hatch lint env to linting

- doc/operator_auth.md
- packaging/Makefile
- pyproject.toml
- src/aleph/vm/orchestrator/views/authentication.py
- src/aleph/vm/utils/__init__.py
- tests/supervisor/test_authentication.py
Add Solana authentication method for the VM operator endpoint.
First version on how to implement this. It is the same method as with Ethereum using an ephemeral key, but that key is signed with Solana private key instead of Ethereum.
On the  SignedPubKeyPayload a  `chain` argument that can be either `ETH` or `SOL` so we know which chain signing method to validate against. It default to ETH as to remain backward compatible with current client implementations.
Also added a docstring on the `require_jwk_authentication` decorator. 
Related Jira tickets : ALEPH-50
Not really much to test as the client part (Python/ web) is not developed yet. So you will have to rely on the tests.
N/A
This add the new dependency Solathon to sign and validate the signature via a Solana wallet, it itself use the …
> Problem: Solana wallet  couln't be used to control the VM

- examples/example_confidential_image/build_debian_image.sh
Fix  the disk creation script to add a more clean message when any step fail.
Related ClickUp, GitHub or Jira tickets : ALEPH-211
- [N/a] An LLM was used to review the new code and look for simplifications.
- [N/a] New classes and functions contain docstrings explaining what they provide.
- [N/a] All new code is covered by relevant tests.
- [N/a] Documentation has been updated regarding these changes.
-
Follow the step described there https://docs.aleph.im/computing/confidential/encrypted-disk/
Upload here screenshots or videos showing the changes if relevant.
-
> Display message when CoCo disk creation abort

- src/aleph/vm/orchestrator/tasks.py
Problem:
When aleph-vm was starting if the vm-connector couldn't connect to the pyaleph API , the startup crashed and systemd restarted it in a loop.
Solution:
Stop registering the sample program at startup, so the  pyaleph api don't need to be reached at startup. This code was left as a demo but it didn't really do anything  at the moment.
We have just commented the code if we want to reuse it in the future.
Jira ticket : ALEPH-111
stop your pyaleph and restart aleph-vm
A more complete and long analysis of the problem, along with different proposed solution is in the comment of the  JIRA ticket
https://aleph-im.atlassian.net/browse/ALEPH-111?focusedCommentId=10008
> Fix: Error fetching message from vm-connector for start_watch_for_messages_task

- src/aleph/vm/orchestrator/cli.py
Solution : Add the release number to sentry init according to the Sentry documentation
https://docs.sentry.io/platforms/python/configuration/releases/
Related ClickUp, GitHub or Jira tickets : ALEPH-124
> Problem: Sentry reporting didn't have release information

- packaging/Makefile
sevctl 0.4.3 was refusing to compile on Ubuntu 22.04 and 24.02
because of some deps. This happened in the Github CI
This prevented the build of package and the testing inside the CI
Solution: Update sevctl to 0.6.0
Error logs
```
Compiling structopt-derive v0.4.18
error[E0658]: `c".."` literals are experimental
--> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kvm-ioctls-0.19.0/src/ioctls/system.rs:99:24
|
99 |         let kvm_path = c"/dev/kvm";
|                        ^^^^^^^^^^^
|
= note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information
error[E0658]: `c".."` literals are experimental
--> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kvm-ioctls-0.19.0/src/ioctls/system.rs:744:24
|
744 |         let kvm_path = …
```
> Problem: sevctl installation broken on Ubuntu

- src/aleph/vm/pool.py
Remove the counter way to assign a vm_id as it didn't work reliably
Jira ticket: ALEPH-272
That method was broken when persistent instances were loaded at start up. Since the "new" feature that allow persistent instance across aleph-vm reboot if one was started then aleph-vm was stopped and restarted the counter method could reassign the ip and break the existing vm's.
Secundary reason was that the feature wasn't working properly with the default settings, as `2**available_bits` returned 1. So that code path was only used if the node owner tweaked some undocumented settings making it hard to identify and debug in prod nodes.
> Make vm_id assignment more robust

- packaging/Makefile
- pyproject.toml
Related Jira tickets : ALEPH-279
Changed the aleph_message dependency to use the last version with new EVM definitions.
Deploy a VM using one of the new ones and check that should work as usually, like with "CHAIN": "POL".
This [PR](https://github.com/aleph-im/aleph-message/pull/116) should be merged before at the deployment time.
> Implement new EVM chains

- src/aleph/vm/orchestrator/run.py
Symptom:
The CustomError from the diagnostics VM was printed even if if IGNORE_TRACEBACK_FROM_DIAGNOSTICS was set to True (the default)
Analysis:
This was caused by the refactoring of the fastapi_example/main.py file done in fe9235ac658915eea20d5371ae45cedabe1f7b17
Which changed the output used to detect the error to catch
Solution:
Fix detection string
> Problem: IGNORE_TRACEBACK_FROM_DIAGNOSTICS broken

- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
Jira ticket: ALEPH-298
some CRN failed on any action with error OSError: [Errno 24] Too many open files:
Solution:
Properly close stream to journald when the VM is stopped
> Problem: error Too many open files

- .github/workflows/test-on-droplets-matrix.yml
CI returned error:
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit. DAMN
Solution: :Use GitHub container repository instead of hub.docker.io (default one for docker)
olethanh pushed the image using:
```bash
podman pull docker.io/alephim/vm-connector:alpha
podman tag alephim/vm-connector:alpha ghcr.io/aleph-im/vm-connector:alpha
podman push ghcr.io/aleph-im/vm-connector:alpha
```
Auth to github firt https://docs.github.com/fr/packages/working-with-a-github-packages-registry/working-with-the-container-registry
Related ClickUp, GitHub or Jira tickets : ALEPH-315
> CI: docker: Error response from daemon: toomanyrequests

- pyproject.toml
- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/cli.py
- src/aleph/vm/orchestrator/custom_logs.py
- src/aleph/vm/orchestrator/metrics.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/version.py
- tests/supervisor/views/test_operator.py
Split of from #719 , better reviewability.
Improve the logging for ALEPH-VM
This is a lot of small improvement to make aleph-vm more usable. I'm putting them all under the banner of the  Jira tickets : ALEPH-166
* Include the VM hash in logs were relevant (might have missed some place yet) to help debug endpoint
* Remove the duplicate output of the  db  logs (sqlalchemy)
* Ensure logs for http request are printed
* Set default level for logging to INFO (so node owner have useful info by default for debugging problem)
* Fix `hatch fmt` command (and `ruff fmt` )
* Less crap in the program output in general
* Don't check payment for fake debug instances.
* Ability to set the LOG level via an environment variable  (replace https://github.com/aleph-im/aleph-vm/pull/581 )
Related ClickUp, …
> Improve logging, Add logging per VM

- README.md
- TESTING.md
- src/aleph/vm/models.py
- src/aleph/vm/pool.py
- tests/supervisor/test_authentication.py
- tests/supervisor/test_instance.py
Split of from #719, to improve reviewability.
Document how to do the developer setup.
> Improve documentation for contributors

- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/metrics.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/views/operator.py
- tests/supervisor/views/test_operator.py
Add a endpoint to get log from  program from history, even after they have run.
Related ClickUp, GitHub or Jira tickets : ALEPH-275
Related Client PR https://github.com/aleph-im/aleph-client/pull/304
add `/control/machine/{ref}/logs.json`
Use the related branch in the client `ol-ALEPH-275-info-program-boot` or check the unit test. You can also call the endpoint by hand
> Add json logs endpoint which works for finished execution

- README.md
- examples/example_django/manage.py
- pyproject.toml
- runtimes/aleph-debian-12-python/init1.py
- src/aleph/vm/hypervisors/qemu_confidential/qemuvm.py
- src/aleph/vm/orchestrator/custom_logs.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/authentication.py
- src/aleph/vm/orchestrator/views/operator.py
- tests/supervisor/test_authentication.py
- tests/supervisor/test_instance.py
- tests/supervisor/test_qemu_instance.py
- tests/supervisor/test_utils.py
- tests/supervisor/test_views.py
- tests/supervisor/views/test_operator.py
Switch to ruff for formatting (not linting) instead of black.
To clarify, ruff has two mode:
*  formatting, launched with `ruff format` or `hatch fmt --formatter`,  which is more or less equivalent to `black`
* linting, lauched with `ruff --fix` or `ruff check fix` or `hatch fmt --linter`, which check the code style more comprehensively  and which fixes can't always be automated.
The builtin command `hatch fmt` launch both. But in aleph-vm we use `hatch linting:fmt` (or `linting:style` ) that do a whole bunch additional checks (yaml, pyproject.toml, etc..)
This PR remove `black` execution from the fmt/style scripts in hatch but keep it configured and installed for now (so we can double check and to ease transition)
The ruff  configuration is also modified so it match what isort  do. We …
> Use ruff for formatting and document code quality

- src/aleph/vm/network/interfaces.py
JIRA: ALEPH-115
**Problem**:
When reusing an existing stale network interface, the following error would occasionally occur:
```
Unknown exception while deleting address 2a01:4f8:171:787:1:63fa:f8b5:db10/124 to interface vmtap...
```
See details in Sentry: [https://alephim.sentry.io/issues/5993120643/?project=4506303231819776](https://alephim.sentry.io/issues/5993120643/?project=4506303231819776)
**Analysis**:
This error occurred during the process of cleaning up an old interface (that was not deleted after usage for various possible reasons). The code was attempting to delete the IP addresses associated with this interface (as calculated in the code). However, when these IP addresses did not exist, an error was raised.
**Solution**:
Our initial approach was to use the `IPRoute` module to …
> Fix error Deleting network interface

- pyproject.toml
Reopening #732 since dependabots can't execute CI
---
updated-dependencies:
- dependency-name: aiohttp
dependency-type: direct:production
...
> Chore(deps): Bump aiohttp from 3.9.5 to 3.10.11

- src/aleph/vm/orchestrator/tasks.py
Make monitory_payment never stop
= Problem
Reported by user “Roby” on Telegram with his own CRN and VMs. PAYG Instance he had deleted from the web frontend never stopped running.
= Analysis
After some investigation and dicussion with the user, the probable cause is that the monitor payment task has crashed and stopped. Thus VM didn’t get stopped anymore this way. (when forgotten or failing payment)
Upon investigation there is no error handling over the whole task thus in case of uncatched exception the whole task stopped.
= Solution
Wrap the monitor_payment task around a try_catch so it never stop running
> Problem Deleted Instance not stopping - monitor_payment

- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/storage.py
- tests/supervisor/test_execution.py
idem for empty mount name.
Fix problem when a client attached a persistant volume to a vm without a name
We put a numerical name
Related ClickUp, GitHub or Jira tickets : ALEPH-307
Create a VM with a volume without a name or mount name
>  Add a name for Volume at start if not present

- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
- src/aleph/vm/hypervisors/qemu_confidential/qemuvm.py
Ticket: JIRA-344
Problem:
When QEMU was failing to boot the hard drive file image provided by the user, for example we have cases of user  using an ext4 image for firefracker
instead of a qemu disk image (this was facilitated by an oversight in the typescript sdk), the qemu process and hence the controller would hang indefinetly
without showing an error message.
Analysis
1. the Boot process was not part of the logs or the process output. (even inside the server) which is part of what was making it hard to debug.
2. QEMU try to boot via the network even if it is useless
3. After failing all boot method the qemu process and thus the controller  is still running indefinitely
Solution:
Change the option for qemu
-nographics make it output the boot process on the standard output (and thus the …
> Fix Qemu hang silently on failed boot

- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/utils/logs.py
- tests/supervisor/test_log.py
Jira ticket: ALEPH-316
At some point the websocket endpoint stopped sending log entries to client
"aleph instance logs" output gets stuck
VM started and is accessible, but logs seem frozen when querying them via CLI.
The log entries are in journald and retrievable but they don't get put at on the internal queue. My guess is that there is a lock bug between the journal polling and the queue max length, probably that if the queue is full and get emptied, the polling doesn't reset unless new message arrive in journald.
Rework the journald to Queue implementation.
I have tried a lot of combinaison and variation of the logic and rewrote that code block multiple times, this version works as far as I can tell.
The interaction between asyncio select handling, journald fd reset and async task is …
> Fix VM logs websocket endpoint getting stuck

- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/storage.py
If a message was inexisting, fake or rejected, for example in the ref for an instance, update_allocation halted at the VM it was processing,  stopping the processing of the rest of the list of VM. This mean that any bad item hash from the scheduler would block bringing any new VM ups.
This situation is now improved more generally so as to catch any error that might happen during VM creation.
Related ClickUp, GitHub or Jira tickets : Jira Ticket: ALEH-337
- [no] All new code is covered by relevant tests.
- [n/a] Documentation has been updated regarding these changes.
- [ x] Dependencies update in the project.toml have been mirrored in the Debian package build script `packaging/Makefile`
Explain the changes that were made. The idea is not to list exhaustively all the changes made (GitHub …
> update allocation halted on missing hash ALEPH-337

- src/aleph/vm/orchestrator/run.py
or not being downloadable
Related ClickUp, GitHub or Jira tickets : ALEPH-353
When calling an program on a CRN, whose message the CRN couldn’t reach, it returned the error
```
500: Unhandled error during initialisation
```
instead of a proper explanation error
Catch that error. Catch also the other possible error when downloading
This also now works when failing to download a runtime or volume
Call your CRN via http with an invalid item hash
> Display proper error for message not found

- src/aleph/vm/guest_api/__main__.py
Sentry Issue: ALEPH-VM-STAGING-41
Jira Issue: ALEPH-353
This error was making the diagnostic down constently, raising 3K error in 48h on Sentry
In aleph.vm.guest_api._main_.put_in_cache
```
ConnectionClosedError: Reader at end of file
File "aiohttp/web_app.py", line 569, in _handle
return await handler(request)
File "aleph/vm/guest_api/__main__.py", line 128, in put_in_cache
return web.json_response(await redis.set(f"{prefix}:{key}", value, expire=CACHE_EXPIRES_AFTER))
```
*Investigation*
The error started at Jan 12, 2025 7:26:47 AM CET
The redis server was restarted around the same time by the server unattended-upgrades (apt)
*Analysis*
The guest api for the diagnostic VM lost the connexion to the redis server (via unix connexion) when it was restarted. Since the guest api always reuse …
> Fix guest-api ConnectionClosedError: Reader at end of file

- src/aleph/vm/pool.py
Temporary disable tearing down the network when stopping supervisor Fix issue of persistent instances running inside systemd controller losing their ipv4 Nat access upon supervisor restart or upgrade.
Github issue https://github.com/aleph-im/support/issues/9
this is a temporary hotfix till we have a better solution for handling the network
> Fix instance ip4 network stopping (nat)

- src/aleph/vm/orchestrator/status.py
Jira Issue: ALEPH-355
Sentry Issue: ALEPH-VM-STAGING-2G
Problem:
Code was asserting that result is always true but the diagnostic vm can return False or True for the ip check, so  the whole status_check_fastapi was failing
Solution:
return its result instead of expecting true
> Fix AssertionError  aleph.vm.orchestrator.views.status_check_fastapi

- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/storage.py
Problem: If a user wants to attach a volume that have a name with spaces or other weird symbols, it raises an error and don't allocate the VM.
Solution: Sanitize the volume name before creating it.
Applied a regular expression to replace invalid characters for an `_`
Try to execute an instance or a program with a volume name with spaces or weird characters on their name.
> Sanitize volume names

- runtimes/aleph-debian-12-python/init1.py
The runtime init `init1.py` emitted the signal `0x4321fedc`
to the Linux kernel when shutting down.
The correct procedure [according to the Firecracker docs]
(https://github.com/firecracker-microvm/firecracker/blob/dfb45dc4213bcb1c9704435457e233d3a210dce2/docs/getting-started.md?plain=1#L298) is to issue a `reboot`.
The syscall number for a reboot on Linux is `0x1234567`.
Tested using Firecracker independently of `aleph-vm`.
> Fix: Runtime emitted wrong reboot signal

- src/aleph/vm/orchestrator/tasks.py
Problem: in monitoring_payment_task
the check of stream payment was not done
Regression introduced in https://github.com/aleph-im/aleph-vm/pull/726
Related ClickUp, GitHub or Jira tickets : none
- [:(] All new code is covered by relevant tests.
> Fix regression: Monitoring of payment stream

- packaging/aleph-vm/etc/needrestart/conf.d/aleph-vm.conf
Confidential VMs are restarted automatically
Related ClickUp, GitHub or Jira tickets : ALEPH-383
Problem: On Ubuntu 24.04 OS version, a new service called `needrestart` restart some services automatically and this also resets some confidential VMs that cannot init again as we don't store the password key.
Solution: Add a rule on `needrestart` service to skip the restart on aleph services.
Install the version on a CRN with some instances inside and do a manual package update.
> Solve Aleph VMs automatic restarts

- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/utils.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/resources.py
- tests/supervisor/test_checkpayment.py
WIP
Related ClickUp, GitHub or Jira tickets : ALEPH-401
If a specific config is required explain it here (account, data entry, ...)
Upload here screenshots or videos showing the changes if …
> Check community payment flow

- src/aleph/vm/garbage_collector.py
Add a script to manually  list and remove volume linked to inactive VM. It fetches data from the scheduler and pyaleph main's node as to fetch information on the status of the VM. Then display them to the user to determine if they can be removed safely.
JIRA ticket ALEPH-37
This solution is a stop gap to run manualy till we have  more confident in it and can automatically run it in the background
> Garbate collector: Free disk space from inactive VM

- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/utils.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/static/helpers.js
- src/aleph/vm/orchestrator/views/static/main.css
- src/aleph/vm/orchestrator/views/templates/index.html
- src/aleph/vm/pool.py
- src/aleph/vm/resources.py
- tests/supervisor/test_checkpayment.py
Implemented a settings aggregate query to check the compatible GPUs that we support and also other general settings.
Feature: Added options to get GPU compatibilities from a settings aggregate.
Go to the `/about/usage/system` endpoint on a CRN with at least 1 GPU and check if the `compatible` field appears and also the `model` one.
> Implemented GPU compatibility system

- src/aleph/vm/conf.py
If a specific config is required explain it here (account, data entry, ...)
Upload here screenshots or …
> Default log level to info

- packaging/Makefile
- src/aleph/vm/pool.py
Fix parse error that prevented Supervisor from starting when loading persistant executions, as it could not parse the gpu field
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/opt/aleph-vm/aleph/vm/orchestrator/__main__.py", line 4, in <module>
main()
File "/opt/aleph-vm/aleph/vm/orchestrator/cli.py", line 379, in main
supervisor.run()
File "/opt/aleph-vm/aleph/vm/orchestrator/supervisor.py", line 184, in run
asyncio.run(pool.load_persistent_executions())
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File …
> Fix start error in  load_persistent_executions

- examples/example_fastapi/main.py
This fix issue reported by node owner where if they enable a ipv6 and it's not working, it also break the diagnostic /internet check
> Fix DiagnosticVM, force ipv4 connexion on /internet check

- packaging/Makefile
- packaging/debian-12.dockerfile
- packaging/ubuntu-22.04.dockerfile
- packaging/ubuntu-24.04.dockerfile
- pyproject.toml
Error in CI https://github.com/aleph-im/aleph-vm/actions/runs/13458482852/job/37788353003
pip3 install --progress-bar off --target ./aleph-vm/opt/aleph-vm/ 'aleph-message==0.6' 'eth-account==0.10' 'sentry-sdk==1.31.0' 'qmp==1.1.0' 'aleph-superfluid~=0.2.1' 'sqlalchemy[asyncio]>=2.0' 'aiosqlite==0.19.0' 'alembic==1.13.1' 'aiohttp_cors==0.7.0' 'pyroute2==0.7.12' 'python-cpuid==0.1.0' 'solathon==1.0.2' 'protobuf==5.28.3'
Collecting aleph-message==0.6
Downloading aleph_message-0.6.0-py3-none-any.whl (17 kB)
Collecting eth-account==0.10
Downloading eth_account-0.10.0-py3-none-any.whl (109 kB)
Collecting sentry-sdk==1.31.0
Downloading sentry_sdk-1.31.0-py2.py3-none-any.whl (224 kB)
Collecting qmp==1.1.0
Downloading qmp-1.1.0-py3-none-any.whl (11 kB)
Collecting aleph-superfluid~=0.2.1 …
> Attempt to fix the packaging issue on Ubuntu 22.02

- pyproject.toml
Fix the CI issues by using a new version of python-cpuid.
> Fix: Used old versionof python-cpuid

- packaging/aleph-vm/etc/systemd/system/aleph-vm-supervisor.service
Wants=
Configures (weak) requirement dependencies on other units.
Requires=
Similar to Wants=, but declares a stronger requirement dependency.
If this unit gets activated, the units listed will be activated as well. If one of the other units fails to activate, and an ordering dependency After= on the failing unit is set, this unit will not be started. Besides, with or without specifying After=, this unit will be stopped (or restarted) if one of the other units is explicitly stopped (or restarted).
Documentation: https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html
> Fix: Supervisor was restarted when Kubo crashed

- src/aleph/vm/garbage_collector.py
Server api1.aleph.im is very slow and outdated
(Core i7 from 2018, up to 40 seconds to respond
to `/metrics` in the monitoring).
We suspect that this causes issues in the
monitoring and performance of the network.
This branch removes all references to api1 and
replaces them with api3 where relevant.
> Fix: Remove references to slow server api1.aleph.im

- packaging/Makefile
Put the correct aleph-message version on the package generation script.
Increment `aleph-message` package version on Makefile for package generation.
> Increment `aleph-message` package version

- src/aleph/vm/conf.py
Adding type annotation for a better code clarity and safety. This has been done on the migration of pydantic branch, but adding it first because it should not break the code and facilitate the merge of the pydantic PR
Adding type annotation in the conf.py file for a better clarity and safety.
Due to the change mypy raised those errors because os.makedirs expects a valid path but variables can be None.
changes have been done about the path validation
```
src/aleph/vm/conf.py:412: error: Argument 1 to "makedirs" has incompatible type "Path | None"; expected "str | bytes | PathLike[str] | PathLike[bytes]"  [arg-type]
src/aleph/vm/conf.py:413: error: Argument 1 to "makedirs" has incompatible type "Path | None"; expected "str | bytes | …
```
> Fix: Missing type annotation

- src/aleph/vm/network/hostnetwork.py
> Allow /56 subnet for ipv6 pool

- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/cli.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/utils.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/pool.py
- src/aleph/vm/resources.py
- tests/supervisor/test_resources.py
- tests/supervisor/test_views.py
Implement a resource (GPU) reservation system. 
Please do not squash when merging.
This new feature prevent resources being taken between the moment the user initiate the payment flow and the moment the VM start.
Jira tickets : ALEPH-421
- Add a new endpoint `/control/reserve_resource` which reserve the required resource to start the VM for the user. At the moment it only reserve GPU.
- Added `reservations` attributes on `VmPool` that handle the list of reservations.
- Check and free the reservation when staring a new VM. 
- When inspecting the earlier code, I noticed that if no GPU were available the  VM probably started without the GPU, now the VM doesn't start and raise an error
- pool.setup() is now async, to allow working in the unit tests.
Need a CRN with GPU. I tested  principally …
> Gpu Reservation system

- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/pool.py
- tests/supervisor/test_views.py
of vm when calculate available disk space
Jira: ALEPH-420
This will help the scheduler scheduler more properly the available resource on CRN
Alternative approach to https://github.com/aleph-im/aleph-vm/pull/780 as Sparse file were not properly created.
- the behaviour to expect, e.g: tooltip has purple …
> Usage system: remove reserved usage for volumes

- src/aleph/vm/orchestrator/cli.py
- src/aleph/vm/orchestrator/tasks.py
This is a lot of small improvement to make aleph-vm more usable. I'm putting them all under the banner of the  Jira tickets : ALEPH-166
* Better logging
* Include the VM hash in logs were relevant (might have missed some place yet) to help debug endpoint
* Remove the duplicate output of the  db  logs (sqlalchemy)
* Ensure logs for http request are printed
* Set default level for logging to INFO (so node owner have useful info by default for debugging problem)
* Improve the developer documentation
* Fix some tests precondition
* Fix docstirngs
* Fix `hatch fmt` command (and `ruff fmt` )
* Less crap in the program output in general
* Don't check payment for fake debug instances.
* Ability to set the LOG level via an environment variable  (replace …
> Ol aleph 166 misc stability

- packaging/Makefile
This bumps their versions to
- Firecracker 1.5.0 -> 1.7.0
Most changes related to Firecracker are regarding
the snapshots, which are not used by `aleph-vm`.
> Fix: Upgrade Firecracker 1.5.0 -> 1.7.0 

- .github/workflows/build-deb-package-and-integration-tests.yml
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/pool.py
Fix the issue with VM starting and not freeing resource properly
Related ClickUp, GitHub or Jira tickets : ALEPH-287 ALEPH-471
> Fix VM lifecycle and blocking resource. 

- src/aleph/vm/hypervisors/qemu/qemuvm.py
Important note: Previously --no-reboot was used so if the BIOS failed to boot the VM because of for example an invalid disk image provided by the user then the QEMU process and the controller would halt. The new behaviour is that the VM will reboot indefinetly. But it should be catched by the wait for init procedure that will test by ping.
This new modification was necessary because the GPU VM need a reboot for their setup. And generaly user would be confused when rebooted VM would not restart.
The --no-reboot flag was kept for ConfidentialVM as confidential VM do not support reboot anyway
Related ClickUp, GitHub or Jira tickets : JIRA: ALEPH-472
> enh: allow user to reboot from inside the VM

- src/aleph/vm/orchestrator/views/authentication.py
- tests/supervisor/test_authentication.py
make it more clear what the error is so it is easier for client and sdk developper to debug auth problem
Explain how to test your …
> enh: Operator auth. Better http error

- examples/example_fastapi/main.py
- packaging/Makefile
- pyproject.toml
- src/aleph/vm/conf.py
- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/controllers/configuration.py
- src/aleph/vm/hypervisors/firecracker/config.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/README.md
- src/aleph/vm/orchestrator/chain.py
- src/aleph/vm/orchestrator/reactor.py
- src/aleph/vm/orchestrator/resources.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/authentication.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/pool.py
- src/aleph/vm/resources.py
- src/aleph/vm/storage.py
- src/aleph/vm/utils/__init__.py
- tests/supervisor/test_checkpayment.py
- tests/supervisor/test_gpu_x_vga_support.py
- tests/supervisor/test_views.py
Feature: Migrate Pydantic V1 to V2.
1. We updated model validation in operator.py to use model_validate instead of parse_obj
2. We fixed json methods in resources.py and configuration.py to use model_dump_json instead of json
3. We updated the import from pydantic.json to pydantic_core in models.py
4. We fixed the display method in conf.py to use model_config directly
Deploy that version on the staging CRNs and ensure that everything is working well.
> Migrate Pydantic V1 to V2

- src/aleph/vm/storage.py
Since the pydantic upgrade the / is automatically added thus it resulted in a double // e.g http://localhost:4021//download/data/5f31b0706f59404fad3d0bff97ef89ddf24da4761608ea0646329362c662ba5 which made the vm-connector return 404
It was fixed for other download function from the vm connector but this one was missed
> FIX downloading volume from connector

- docker/vm_supervisor-dev.dockerfile
- examples/volumes/Dockerfile
- packaging/Makefile
- runtimes/aleph-debian-12-python/create_disk_image.sh
- src/aleph/vm/orchestrator/README.md
Fix: Upgrade `aleph-message` version dependency to 1.0.0.
Fix: Upgrade `aleph-message` version dependency to 1.0.0.
Execute the supervisor and check that everything is working well.
> Upgrade `aleph-message==1.0.0` version dependency

- src/aleph/vm/hypervisors/qemu_confidential/qemuvm.py
ConfidentialQemuVM teardown was trying to close the journal stdout but they were not properly set. (they are set properly in qemuvm)
```
python3[1738237]: 2025-04-14 13:41:13,531 | ERROR | Task exception was never retrieved
python3[1738237]: future: <Task finished name='Task-3' coro=<QemuVM.stop() done, defined at /opt/aleph-vm/aleph/vm/hypervisors/qemu/qemuvm.py:180> exception=AttributeError("'QemuConfidentialVM' object has no attribute 'journal>
python3[1738237]: Traceback (most recent call last):
python3[1738237]:   File "/opt/aleph-vm/aleph/vm/hypervisors/qemu/qemuvm.py", line 184, in stop
python3[1738237]:     if self.journal_stdout and self.journal_stdout != asyncio.subprocess.DEVNULL:
python3[1738237]:        ^^^^^^^^^^^^^^^^^^^
```
Related ClickUp, GitHub or Jira tickets : …
> Fix ALPEH-517 confidential clean up

- src/aleph/vm/orchestrator/views/__init__.py
Analysis
The update_allocations endpoint called by the scheduler stopped the  instances as it wasn’t in the scheduler list
Solution
Better check which executions are started via the scheduler
Related ClickUp, GitHub or Jira tickets : ALEPH-518
> ALEPH-518 Fix Confidential and GPU instance  stopping after start

- src/aleph/vm/pool.py
Fix: Solve message class casting issue with requirements field.
Removed InstanceContent casting and put it as ExecutableContent.
Create a VM with GPU and check that the VM is running.
> Solve message requirements casting issue

- examples/example_fastapi/main.py
- src/aleph/vm/orchestrator/status.py
Upgrade diagnostic VM to use an ethereum url that don't return 307
https://ethereum.org changed to now return 307
which make the internet check fail and impact node owner score
Internet check : Accept code other than 200 as proper result
The diagnostic VM use raise_for_error to see if it accept the response
this code check if status_code < 400
> Fix internet check failure 

- src/aleph/vm/pool.py
If a specific config is required explain it here (account, data entry, ...)
Upload here screenshots or …
> Fix reserved space calculation

- src/aleph/vm/controllers/firecracker/instance.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/models.py
- src/aleph/vm/network/firewall.py
- src/aleph/vm/orchestrator/cli.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/pool.py
- src/aleph/vm/systemd.py
- src/aleph/vm/utils/__init__.py
- tests/supervisor/test_checkpayment.py
- tests/supervisor/test_instance.py
- tests/supervisor/test_qemu_instance.py
- tests/supervisor/test_views.py
- tests/supervisor/views/test_operator.py
- tests/supervisor/views/test_view_errors.py
Jira ticket: ALEPH-287
This PR improve how Instance are started, making it more reliable and properly cleaning when they fail to start. It also allow to start again the VM if it failed to start the first time.
Changes introduced by this PR:
1. Decouple instance wait_for_init from allocation. It now return directly after starting the VM controller and run wait_for_init in the background. wait_for_init has been renamed wait_for_boot in VM
2. Stop the controller when the Instance fail to start. Before if the instance failed to respond to ping the Instance was reported as not running and removed from the list but the Instance systemd controller was still. This tied up resource and prevented the VM from starting again. Also it caused issue with the network. 
3. Introduce a new endpoint …
> Retry instances not running add new Execution list endpoint

- docker/vm_supervisor-dev.dockerfile
- examples/volumes/Dockerfile
- packaging/Makefile
- pyproject.toml
- runtimes/aleph-debian-12-python/create_disk_image.sh
- src/aleph/vm/orchestrator/README.md
Feature: Use the last version of aleph-message package.
> Use last `aleph-message` version

- runtimes/aleph-debian-12-python/init1.py
Increase program warmup timeout from 1s to 5s
Programs need to be warmed up before processing HTTP requests. The default 1s timeout is insufficient for some programs, causing stability issues. Increasing to 5s provides adequate warmup time.
> fix: Increase program warmup timeout from 1s to 5s

- src/aleph/vm/orchestrator/machine.py
On some combination of system configuration and OS a parsing of the lshw output issue happened Which made that endpoint return a 500
Related ClickUp, GitHub or Jira tickets : None
> Fix  /about/usage/system on some arch

- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/pool.py
Related Jira ticket : ALEPH-549
Problem:
When the whole server rebooted, internet was not working inside instance and they were unreachable on the network. As the network interface were not properly recreated
Analysis:
At the instance automatic restart once the serevr rebooted, the network interface is not existant, thus QEMU recreating some kind of default network  that is not setup as needed (tunneling, ip address,  nat, ipv6, etc.._ and thus the network inside the instance was non functional.)
Solution:
In the controller, wait for the network interface to be recreated by the supervisor In the supevisor recreate the network interface and set it up if it is not existing This is done this way as it is not possible to add tuntap after the interface is created
How to test:
* Stop the …
> Fix Instance network not working on server reboot

- README.md
- packaging/aleph-vm/etc/haproxy/haproxy-aleph.cfg
- src/aleph/vm/haproxy.py
- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/machine.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/pool.py
- tests/supervisor/test_haproxy.py
Resolve  a few issue I encountered when doing the mass deployment of 1.7.1
1. Fix the Fallback server in haproxy getting removed and rending it unresponsive
2. Fix CPU detection on coco-1
3. Update doc on how to setup the dev env
4. Speed up free port detection for forwarding, making allocate and restart faster.
5. Add a debug endpint for haproxy
6. Log error that get caugh by the json_error_middleware
> Fix HaProxy fallback server and others fixes

- src/aleph/vm/orchestrator/tasks.py
- tests/supervisor/test_checkpayment.py
Related ClickUp, GitHub or Jira tickets : ALEPH-572
Handle 2 new message status `REMOVING` and `REMOVED` for the payments check
Create an instance on a CRN and then remove the funds to get the message status on REMOVING and then on REMOVED. On REMOVING status should maintain the VM working and when the status pass to REMOVED should stop it.
> Handle 2 new message status

- src/aleph/vm/orchestrator/payment.py
- src/aleph/vm/orchestrator/views/__init__.py
- tests/supervisor/test_checkpayment.py
Feature: Support Credits payment method on the notify endpoint.
Integrated credits payment method on the notify endpoint
Try to send an instance using credits payment method and notify it on the CRN.
> Implement Credits payment on Notify endpoint
