- .dockerignore
- .gitignore
- docker/run_vm_connector.sh
- docker/vm_connector.dockerfile
- examples/Makefile
- examples/data/example.json
- firecracker/microvm.py
- vm_connector/main.py
- vm_connector/tests/test_message.json
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
- vm_supervisor/models.py
- vm_supervisor/storage.py
- vm_supervisor/supervisor.py
The Network Connector proxies messages and data from the Aleph Network to the VM Supervisor.
> Feature: Add a network connector

- firecracker/microvm.py
- runtimes/aleph-alpine-3.13-python/init0.sh
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
- vm_supervisor/pool.py
- vm_supervisor/vm/firecracker_microvm.py
> Feature: Make VM network optional

- examples/example_fastapi_2/__init__.py
- firecracker/microvm.py
- guest_api/__main__.py
- runtimes/aleph-alpine-3.13-python/init0.sh
- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/README.md
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
- vm_supervisor/storage.py
- vm_supervisor/supervisor.py
- vm_supervisor/vm/firecracker_microvm.py
This makes it easier to profile the performance of
an Aleph VM.
> Feature: Add profiling logs and --benchmark CLI

- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
- vm_supervisor/models.py
- vm_supervisor/pool.py
- vm_supervisor/supervisor.py
After every execution, a VM is kept running for in case the same function gets called again.
The VM is stopped if no call is made during a configurable duration.
> Feature: Keep a VM ready to accept another call

- examples/message_from_aleph.json
- firecracker/microvm.py
- runtimes/aleph-alpine-3.13-python/init0.sh
- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/pool.py
- vm_supervisor/vm/firecracker_microvm.py
It would not work in the next virtual machines launched.
> Fix: Networking was hardcoded for 1st VM

- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/supervisor.py
- vm_supervisor/vm/firecracker_microvm.py
Performance did suffer from this.
Solution: Keep the same app running between calls. Copy the code and data during VM setup instead of doing it at every call.
> Fix: Apps in VMS were restarted for every call

- vm_supervisor/supervisor.py
Message ids are usually encoded in hexadecimal (base16) across Aleph.im, with a length of 64 characters.
These cannot be used in hostnames since the each label from the hostname (between dots) must be from 1 to 63 characters long.
Since hostnames are case insensitive, base64 cannot be used to encode the hashes.
Solution: Accept base32 encoding of the message ids in the hostname.
> Fix: Hostname labels must be < 64 chars

- examples/example_fastapi_2/__init__.py
- guest_api/__main__.py
- runtimes/aleph-alpine-3.13-python/create_disk_image.sh
- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/README.md
The cache is available even after a VM has been teared down,
and is shared between different instances of a VM.
> Feature: Add a cache per VM

- .github/workflows/test-integration-fakedata.yml
- examples/message_from_aleph.json
- vm_supervisor/__main__.py
These builds run the entrypoints from the example
example_fastapi_2 to check that the code is working properly.
> Feature: Add self-hosted CI builds

- docker/vm_supervisor.dockerfile
- examples/message_from_aleph.json
- firecracker/microvm.py
- runtimes/aleph-alpine-3.13-python/init1.py
- vm_connector/main.py
- vm_supervisor/README.md
- vm_supervisor/storage.py
- vm_supervisor/vm/firecracker_microvm.py
> Feature: Add support for code on Squashfs

- .github/workflows/test-integration-fakedata.yml
- firecracker/microvm.py
- vm_supervisor/conf.py
- vm_supervisor/supervisor.py
- vm_supervisor/vm/firecracker_microvm.py
> Fix: A VM corouting kept hanging when the rootfs was invalid

- examples/README.md
- vm_supervisor/README.md
- vm_supervisor/conf.py
- vm_supervisor/supervisor.py
This prevents conflicts when running other software on the host.
> Change: Supervisor listents on port 4020 instead of 8080

- vm_supervisor/vm/firecracker_microvm.py
> Fix: Network interface was not read from config

- tutorials/README.md
- tutorials/REQUIREMENTS.md
Updated the official documentation of the tutorials for mac os users concerning the requirements and local testing
> Tutorial update

- vm_supervisor/run.py
Solution: Add headers that display the program item_hash and current code ref.
> Feature: User could not see which version a VM is running

- guest_api/__main__.py
When a VM opens many connections to Redis (thousands) without restarting, the error "Too many open files" will start appearing in the logs.
This is due to new Redis connections being created but not closed, so they accumulate in memory.
Solution: Reuse a single Redis connection for all calls from the guest API.
> Fix: Redis connections were accumulating

- firecracker/microvm.py
These directories were accumulating on disk.
> Fix: A directory with the numerical id of the VM was not deleted

- firecracker/microvm.py
- runtimes/aleph-alpine-3.13-python/init1.py
> Fix: VM were not properly shutdowm, persistent volumes could be corrupted

- firecracker/microvm.py
- vm_supervisor/models.py
- vm_supervisor/pool.py
- vm_supervisor/supervisor.py
> Hoh fix teardown interfaces

- firecracker/microvm.py
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
> Feature: Add support for error monitoring on Sentry

- vm_supervisor/run.py
- vm_supervisor/vm/firecracker_microvm.py
Solution: Timeout the request after the number of seconds has passed.
Fixes #139
> Fix: VM resource seconds field was ignored

- vm_supervisor/conf.py
> Fix: Sentry DSN appeared in clear in the logs

- packaging/Makefile
- packaging/version_from_git.py
- vm_supervisor/__init__.py
- vm_supervisor/supervisor.py
Solution: Add the version of the software in the HTTP response headers
> Problem: Users could not know the version of Aleph-VM for diagnostic

- packaging/aleph-vm/DEBIAN/control
- vm_supervisor/conf.py
- vm_supervisor/metrics.py
- vm_supervisor/models.py
- vm_supervisor/supervisor.py
- vm_supervisor/utils.py
- vm_supervisor/views.py
The resources used by a VM during its execution are recorded in an SQLite database.
The detailed information about VM executions can optionally be stored in JSON files on disk.
> Feature: Record VM execution times and log details on files.

- vm_supervisor/views.py
Solution: Only allow HTTP method GET to access the index page.
> Fix: Querying index with HTTP HEAD raised 500 due to AssertionError

- firecracker/config.py
- packaging/Makefile
- vm_supervisor/README.md
> Dependency: Upgrade Firecracker to v1.0.0

- vm_connector/main.py
I would not squash these commits.
> Fix and cleanup vm_connector

- vm_supervisor/status.py
Co-authored-by: aliel <ali.elb@gmail.com>
> Fix: Concurrent requests could result in a different counter value

- packaging/Makefile
Changelog: https://github.com/firecracker-microvm/firecracker/releases/tag/v1.1.0
> Chore: Update firecracker to 1.1.0

- examples/example_fastapi/main.py
- vm_supervisor/run.py
- vm_supervisor/status.py
- vm_supervisor/views.py
>  Fix: A VM would not restart if the init process crashes

- examples/example_http_js/README.md
- examples/example_http_rust/README.md
- tutorials/REQUIREMENTS.md
> Fix: Examples doc typos

- firecracker/config.py
- firecracker/microvm.py
- firecracker/models.py
- vm_supervisor/conf.py
- vm_supervisor/storage.py
- vm_supervisor/vm/firecracker_microvm.py
The custom type did not bring any value to the codebase.
> Internal: FilePath type can be replaced with pathlib.Path

- firecracker/microvm.py
- guest_api/__main__.py
- packaging/Makefile
- vm_supervisor/__init__.py
- vm_supervisor/__main__.py
- vm_supervisor/conf.py
- vm_supervisor/messages.py
- vm_supervisor/models.py
- vm_supervisor/pool.py
- vm_supervisor/reactor.py
- vm_supervisor/run.py
- vm_supervisor/status.py
- vm_supervisor/storage.py
- vm_supervisor/supervisor.py
- vm_supervisor/tasks.py
- vm_supervisor/version.py
- vm_supervisor/views.py
- vm_supervisor/vm/__init__.py
- vm_supervisor/vm/firecracker_microvm.py
Cleanup multiple warnings without affecting the behaviour.
> Cleanup: Code cleanup

- .github/workflows/test-on-droplet.yml
- runtimes/aleph-alpine-3.13-python/init1.py
- vm_supervisor/conf.py
- vm_supervisor/vm/firecracker_microvm.py
This was breaking the `ip route add` command in the initialisation of VMs.
> Fix: Network route should not contain IP mask

- vm_supervisor/conf.py
- vm_supervisor/pool.py
And there was no validation on network prefix sizes.
> Fix: Network configuration was little documented

- doc/INSTALL-Debian-11.md
- doc/INSTALL-Ubuntu-20.04.md
The install guides mentioned 0.2.4 instead of 0.2.5.
> Fix: link to latest version in install guides

- .github/workflows/build-deb-package.yml
This removes a deprecation warning in CI.
> Chore: Update GitHub Actions version

- .github/workflows/test-on-droplet-debian-11.yml
- .github/workflows/test-on-droplet-ubuntu-22.04.yml
The error message was:
```
Could not get lock /var/lib/apt/lists/lock. It is held by process 1399 (apt-get)
E: Unable to lock directory /var/lib/apt/lists/
```
> Fix: CI failed due to apt lock being held

- .github/workflows/code-quality.yml
- firecracker/microvm.py
- vm_supervisor/metrics.py
- vm_supervisor/network/hostnetwork.py
- vm_supervisor/reactor.py
- vm_supervisor/status.py
- vm_supervisor/storage.py
- vm_supervisor/tasks.py
- vm_supervisor/utils.py
- vm_supervisor/views.py
- vm_supervisor/vm/firecracker/executable.py
- vm_supervisor/vm/firecracker/instance.py
- vm_supervisor/vm/firecracker/program.py
Depends on https://github.com/aleph-im/aleph-vm/pull/325
This fixes all basic warnings reported by `black` `isort` and `mypy` and uses `pathlib.Path` more generally.
> Fix warnings from black, isort and mypy

- vm_supervisor/utils.py
- vm_supervisor/vm/firecracker/instance.py
Implement a method to ping a machine and use it on `wait_for_init` method on instances.
> Implement wait_for_init method on instances

- .github/workflows/test-new-runtime-examples.yml
- .github/workflows/test-on-droplet-debian-11.yml
- .github/workflows/test-on-droplet-ubuntu-22.04.yml
- packaging/aleph-vm/DEBIAN/control
- vm_supervisor/vm/firecracker/instance.py
Fixes a few issues that made CI fail when scheduling persistent instances.
> Fix CI failing

- tutorials/README.md
Solution: add sub-command upload
> Fix: Outdated command in tutorials

- packaging/Makefile
Solution:
- Update link to v1.3.3
- Update cp command to exclude files with .debug extension
> Update: Upgrade to Firecracker v1.3.3

- runtimes/aleph-debian-11-python/init1.py
Fixes some typos, formatting.
The runtime moved to using the aleph-sdk-python, closing an aiohttp session is not required anymore.
> Fix: Issues in init1.py

- .github/workflows/test-new-runtime-examples.yml
- .github/workflows/test-on-droplet-debian-11.yml
- .github/workflows/test-on-droplet-debian-12.yml
- .github/workflows/test-on-droplet-ubuntu-22.04.yml
- docker/vm_supervisor-dev.dockerfile
- examples/volumes/Dockerfile
- packaging/Makefile
- vm_supervisor/README.md
- vm_supervisor/conf.py
Problem: we shipped aleph-message 0.4.0a2 instead of the latest 0.4.0.
> Fix: CI was broken because of aleph-message

- examples/example_fastapi/main.py
- firecracker/microvm.py
- packaging/Makefile
- tests/supervisor/test_jwk.py
- vm_supervisor/supervisor.py
- vm_supervisor/views/operator.py
Problem: instance owners wish to perform operations on their VMs like rebooting, streaming logs, etc.
Solution: provide a set of authenticated endpoints.
> Feature: instance operator API

- vm_supervisor/views/__init__.py
Problem: the check to stop persistent programs is too broad and includes instances in the list when checking which persistent programs were unscheduled.
Solution: check both instances and programs at the same time to reduce redundancy.
> Fix: supervisor stops instances for no reason

- vm_supervisor/models.py
In particular, when recording the resource usage of the VM, the database raised the error `UNIQUE constraint failed: records.uuid
External`.
> Fix: Concurrent calls to stop() caused issues.

- doc/INSTALL-Debian-11.md
- doc/INSTALL-Debian-12.md
- doc/INSTALL-Ubuntu-22.04.md
Preparing a Release Candidate for aleph-vm.
Todo:
> Release candidate: 0.2.9-rc1

- src/aleph/vm/models.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/storage.py
Problem: The timezone of the system was often used for dates. This can cause inconsistencies and should be avoided in favour of UTC.
> Fix: Dates did not use UTC

- src/aleph/vm/orchestrator/cli.py
- src/aleph/vm/orchestrator/reactor.py
- src/aleph/vm/orchestrator/run.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/operator.py
- Fix: Initializing VM Pool had side effects
- Fix: Pool singleton caused issues in tests
> Attach loop singleton to aiohttp `app` singleton.

- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/static/helpers.js
- src/aleph/vm/orchestrator/views/static/main.css
- src/aleph/vm/orchestrator/views/templates/index.html
Allow node operators to easily monitor their node metrics using the aleph scoring messages and a resizable/pannable graph.
> Feature: Add a graph for the latest node metrics

- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/orchestrator/views/operator.py
Users could open an unlimited number of queues containing an unlimited number of messages.
> Fix: Users could fill all RAM using queues

- src/aleph/vm/storage.py
Solution: Print a dot "." instead.
> Fix: Download progress printed nothing ("")

- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/authentication.py
- src/aleph/vm/orchestrator/views/operator.py
- src/aleph/vm/orchestrator/views/static/helpers.js
- src/aleph/vm/orchestrator/views/templates/index.html
- src/aleph/vm/pool.py
- tests/supervisor/test_jwk.py
- WIP: Fix control enpoints
- WIP: Use pydantic classes in control endpoints
- WIP: Use pydantic classes in control endpoints
> Improve VM control by owner

- src/aleph/vm/orchestrator/views/authentication.py
- src/aleph/vm/orchestrator/views/operator.py
See #458
- Return HTTP 403 instead of 401 where appropriate
- Fix typos, clarify some variable names
> Fix minor issues in #458

- src/aleph/vm/network/firewall.py
If the nat table was not present we already tried to create it but the command execution order was not correct and tried to add a chain to it before creating it
Solution: The chain creation command was attempted immediatly while the other command were put in a patch, put that ocmmand in a batch too
> Problem: nftables chain initialization failed if no nat table present

- src/aleph/vm/orchestrator/views/operator.py
Not sure this is something we want in general and if it fit our architecture and security design, but I found this modification useful when doing development, it allow accessing the `/control/machines/X/logs` endpoint by passing the same  `X-Auth-Signature` http header that we use for `/control/allocation/` endpoint.
What do you think?
> Allow accessing then logs endpoint using the allocation key auth method

- pyproject.toml
Solution: Fix the version of all dependencies used in the project.
> Fix: CI frequently failed due to new versions

- src/aleph/vm/controllers/__main__.py
- src/aleph/vm/controllers/configuration.py
- src/aleph/vm/controllers/firecracker/executable.py
- src/aleph/vm/controllers/qemu/instance.py
- src/aleph/vm/hypervisors/firecracker/microvm.py
- src/aleph/vm/hypervisors/qemu/qemuvm.py
- src/aleph/vm/pool.py
Run QEMU in systemd as  Firecracker instance do too.
I have  tested and it works but it is best to further test it in different condition and set up. The method to test it is mainly the same as outlined in the QemuPR (see QEMU.md)
This is on top of Andres QEMU branch, i set to be merged in it but it can wait for it to be merged in main too.
We will need to merge it with #496 that handle logging in journald for proper the log endpoint too work
> Run QemuVM in systemd

- docker/vm_supervisor-dev.dockerfile
- examples/volumes/Dockerfile
- packaging/Makefile
- packaging/aleph-vm/etc/ipfs/kubo.json
- pyproject.toml
- src/aleph/vm/conf.py
- src/aleph/vm/orchestrator/README.md
- src/aleph/vm/orchestrator/metrics.py
- src/aleph/vm/orchestrator/payment.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/host_status.py
On top of https://github.com/aleph-im/aleph-vm/pull/512
> Additional improvements and bug fixes for PAYG

- src/aleph/vm/conf.py
- src/aleph/vm/network/interfaces.py
- src/aleph/vm/orchestrator/payment.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/tasks.py
- src/aleph/vm/orchestrator/views/__init__.py
- Fix: TapInterface was not serialized on APIs
- Fix: Browser could not access executions list
- Fix: Browsers could not call APIs due to CORS
- Cleanup: Add comments about HTTP routes
- Fix: Floating point comparisons led to issues
- fixup! Fix: Browser could not access executions list
> Fixes for PAYG

- src/aleph/vm/orchestrator/views/__init__.py
Fixed CORS issue on notify endpoint.
> Solve CORS issue on notify endpoint

- src/aleph/vm/orchestrator/status.py
- src/aleph/vm/orchestrator/supervisor.py
- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/static/helpers.js
- src/aleph/vm/orchestrator/views/templates/index.html
- Fix: Status check using FastAPI used hardcoded VM ID
- Fix: Compatibility with the legacy VM could not be checked
> Add diagnostic for legacy VM

- src/aleph/vm/orchestrator/views/operator.py
Problem: Now the operator API just allow to reboot well ephemeral VMs, not the persistent ones.
Solution: Use the VM Pool to control reboot, stop and erase operations.
> Solve issues on Operator API

- src/aleph/vm/controllers/qemu/instance.py
Fix: Allow aleph-vm to run Qemu instances.
> Allow running Qemu instances

- runtimes/aleph-debian-12-python/create_disk_image.sh
aleph-sdk-python 0.7.0 -> 0.9.0
fastapi 0.103.1 -> 0.109.2
> Update runtime dependencies

- packaging/aleph-vm/etc/systemd/system/aleph-vm-supervisor.service
Solution: Remove the `--very-verbose` argument from the SystemD service definition.
> Fix: Log level was DEBUG instead of WARNING in prod

- src/aleph/vm/orchestrator/supervisor.py
Fix: Solved CORS issues on PAYG creation.
> Solve CORS issue after latest update

- examples/example_fastapi/main.py
Internet connectivity checks by the diagnostic VM relied on a single URL. If that endpoint was down, the internet connectivity of the system was assumed to be down.
Solution: Check connectivity to multiple endpoints in parallel.
> Fix: Internet diagnostic due to single endpoint

- examples/example_http_js/Makefile
- examples/example_http_rust/Makefile
- tutorials/REQUIREMENTS.md
- tutorials/SERVER.md
'aleph program' now need an 'update' argument.
Solution: Update makefile and documentation
> Problem: Makefile for publishing example were not working

- src/aleph/vm/orchestrator/views/__init__.py
- src/aleph/vm/orchestrator/views/operator.py
…t connections
This caused issues when header "X-Auth-Signature" was not passed.
> Fix: Endpoint authenticate_api_request is not adequate for Websocket connections

- tests/supervisor/test_status.py
Fix: Solve failing test, removing it because is not used.
> Solve failing tests on main branch

- pyproject.toml
Updated `aleph-message` package version to 0.4.9
> Fix: Update new `aleph-message` package version.

- docker/vm_supervisor-dev.dockerfile
- examples/volumes/Dockerfile
- packaging/Makefile
- runtimes/aleph-debian-12-python/create_disk_image.sh
- src/aleph/vm/orchestrator/README.md
Fix: Update new `aleph-message` package version on packaging steps.
> Update `aleph_message` package on packaging steps

- src/aleph/vm/orchestrator/views/operator.py
- tests/supervisor/views/test_operator.py
Related ClickUp, GitHub or Jira tickets : ALEPH-94
- [x ] The new code clear, easy to read and well commented.
Use the confidential endpoints. You can check the error code in the tests.
N/A
> Endpoint /confidential/initialize return json error now and proper https status

- .github/PULL_REQUEST_TEMPLATE.md
Add a check for dependencies update
Related ClickUp, GitHub or Jira tickets : none
- [na] New code does not duplicate the functions of builtin or popular libraries.
- [na] An LLM was used to review the new code and look for simplifications.
- [na] New classes and functions contain docstrings explaining what they provide.
- [na] All new code is covered by relevant tests.
- [na] Documentation has been updated regarding these changes.
> Update PULL_REQUEST_TEMPLATE.md for dependencies check

- packaging/Makefile
- pyproject.toml
uprade message to 0.6 so we support GPU field and  T&C
> Upgrade aleph-message to 0.6

- README.md
Minor typo fixed
If a specific config is required explain it here (account, data entry, ...)
Upload …
> Minor typo in README.md fixed

- pyproject.toml
Feature: Upgrade to new `aleph-message` version
> Upgrade `aleph-message` version

- src/aleph/vm/orchestrator/views/templates/index.html
the ipv6 egress check was showing ok even while the test was failing and returning result:False
If a …
> Fix IPv6 egress check on index falesly showing ok

- runtimes/instance-rootfs/create-ubuntu-24-04-qemu-disk.sh
Feature: Create Ubuntu 24.04 QEMU runtime
> Create Ubuntu 24.04 QEMU runtime

- runtimes/aleph-debian-12-python/init1.py
Since Python code runs asynchronously in the same process, sharing the global sys.stdout, prints from an individual call cannot be isolated from other calls.
> Fix: stdout caching caused concurrency issues

- src/aleph/vm/orchestrator/views/__init__.py
Was causing issue when instances failed to start and there was no persistent VM
Jira ticket ALEPH-436 (part of ALEPH-436 )
> Fix  update_allocation error handling  code

- src/aleph/vm/pool.py
Fix: Solve TypeAdapter issue handling with a json data.
When the pool gets the saved execution data, when get the GPU we receive the data in JSON format, so I had to put a `json.loads()` call before passing it to the type adapter.
Restart a CRN with instances running and check that starts well without crashing.
> Solve Pydantic TypeAdapter issue

- .github/workflows/build-deb-package-and-integration-tests.yml
Fix: Solve CI/CD issue with Digital Ocean access token.
> Solve CI/CD issue

- packaging/aleph-vm/etc/haproxy/haproxy-aleph.cfg
- packaging/aleph-vm/etc/haproxy/http_domains.map
- packaging/aleph-vm/etc/haproxy/https_domains.map
- packaging/aleph-vm/etc/haproxy/ssh_domains.map
- src/aleph/vm/haproxy.py
- src/aleph/vm/pool.py
Some fix for the Domain support haproxy config ALEPH-565
And correct review remarks from the previous PR
> domain support haproxy config fix
